<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace dev_t0r\trvis_backend\api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractStationOnLineApi Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractStationOnLineApi
{
    /**
     * POST createStationOnLine
     * Summary: 作成する
     * Notes: 指定のLineに属する StationOnLine を新しく作成する  このデータが属するProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $lineId LineのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function createStationOnLine(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $lineId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing createStationOnLine as a POST method in dev_t0r\trvis_backend\api\StationOnLineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteStationOnLine
     * Summary: 削除する
     * Notes: 既存の StationOnLine を削除する  このデータが属するProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $stationOnLineId StationOnLineのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteStationOnLine(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $stationOnLineId
    ): ResponseInterface {
        $message = "How about implementing deleteStationOnLine as a DELETE method in dev_t0r\trvis_backend\api\StationOnLineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getStationOnLine
     * Summary: 1件取得する
     * Notes: StationOnLine (路線上の駅) の情報を1件取得する  このデータが属するProjectへのREAD権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $stationOnLineId StationOnLineのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getStationOnLine(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $stationOnLineId
    ): ResponseInterface {
        $message = "How about implementing getStationOnLine as a GET method in dev_t0r\trvis_backend\api\StationOnLineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getStationOnLineList
     * Summary: 複数件取得する
     * Notes: 指定のLineに属する StationOnLine (路線上の駅) の情報を複数件取得する  このデータが属するProjectへのREAD権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $lineId LineのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getStationOnLineList(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $lineId
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $p = (key_exists('p', $queryParams)) ? $queryParams['p'] : null;
        $limit = (key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $top = (key_exists('top', $queryParams)) ? $queryParams['top'] : null;
        $message = "How about implementing getStationOnLineList as a GET method in dev_t0r\trvis_backend\api\StationOnLineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT updateStationOnLine
     * Summary: 更新する
     * Notes: 既存の StationOnLine の情報を更新する  このデータが属するProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $stationOnLineId StationOnLineのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateStationOnLine(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $stationOnLineId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing updateStationOnLine as a PUT method in dev_t0r\trvis_backend\api\StationOnLineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
