<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace dev_t0r\trvis_backend\api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractProjectStationApi Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractProjectStationApi
{
    /**
     * POST createProjectStation
     * Summary: 作成する
     * Notes: 指定のProjectに属する Project Station を新しく作成する  このProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $projectId ProjectのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function createProjectStation(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $projectId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing createProjectStation as a POST method in dev_t0r\trvis_backend\api\ProjectStationApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteProjectStation
     * Summary: 削除する
     * Notes: 既存の Project Station を削除する  このデータが属するProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $projectStationId Project StationのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteProjectStation(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $projectStationId
    ): ResponseInterface {
        $message = "How about implementing deleteProjectStation as a DELETE method in dev_t0r\trvis_backend\api\ProjectStationApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getProjectStation
     * Summary: 1件取得する
     * Notes: Project Station の情報を1件取得する  このデータが属するProjectへのREAD権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $projectStationId Project StationのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getProjectStation(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $projectStationId
    ): ResponseInterface {
        $message = "How about implementing getProjectStation as a GET method in dev_t0r\trvis_backend\api\ProjectStationApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getProjectStationList
     * Summary: 複数件取得する
     * Notes: 指定のProjectに属する Project Station (Project内共通の駅) の情報を複数件取得する  このProjectへのREAD権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $projectId ProjectのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getProjectStationList(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $projectId
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $p = (key_exists('p', $queryParams)) ? $queryParams['p'] : null;
        $limit = (key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $top = (key_exists('top', $queryParams)) ? $queryParams['top'] : null;
        $message = "How about implementing getProjectStationList as a GET method in dev_t0r\trvis_backend\api\ProjectStationApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT updateProjectStation
     * Summary: 更新する
     * Notes: 既存の Project Station の情報を更新する  このデータが属するProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $projectStationId Project StationのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateProjectStation(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $projectStationId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing updateProjectStation as a PUT method in dev_t0r\trvis_backend\api\ProjectStationApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
