<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace dev_t0r\trvis_backend\api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractLineApi Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractLineApi
{
    /**
     * POST createLine
     * Summary: 作成する
     * Notes: 指定のProjectに属する Line (路線) を新しく作成する  このProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $projectId ProjectのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function createLine(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $projectId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing createLine as a POST method in dev_t0r\trvis_backend\api\LineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteLine
     * Summary: 削除する
     * Notes: 既存の Line を削除する  このデータが属するProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $lineId LineのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteLine(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $lineId
    ): ResponseInterface {
        $message = "How about implementing deleteLine as a DELETE method in dev_t0r\trvis_backend\api\LineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getLine
     * Summary: 1件取得する
     * Notes: Line (路線) の情報を1件取得する  このデータが属するProjectへのREAD権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $lineId LineのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getLine(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $lineId
    ): ResponseInterface {
        $message = "How about implementing getLine as a GET method in dev_t0r\trvis_backend\api\LineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getLineList
     * Summary: 複数件取得する
     * Notes: 指定のProjectに属する Line (路線) の情報を複数件取得する  このProjectへのREAD権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $projectId ProjectのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getLineList(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $projectId
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $p = (key_exists('p', $queryParams)) ? $queryParams['p'] : null;
        $limit = (key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $top = (key_exists('top', $queryParams)) ? $queryParams['top'] : null;
        $message = "How about implementing getLineList as a GET method in dev_t0r\trvis_backend\api\LineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT updateLine
     * Summary: 更新する
     * Notes: 既存の Line の情報を更新する  このデータが属するProjectへのWRITE権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $lineId LineのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateLine(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $lineId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing updateLine as a PUT method in dev_t0r\trvis_backend\api\LineApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
