<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace dev_t0r\trvis_backend\api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractInviteKeyApi Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractInviteKeyApi
{
    /**
     * POST createInviteKey
     * Summary: 作成する
     * Notes: 指定のWorkGroupに属する招待キーを新規に作成する  指定のWorkGroupへのADMIN権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $workGroupId WorkGroupのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function createInviteKey(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $workGroupId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing createInviteKey as a POST method in dev_t0r\trvis_backend\api\InviteKeyApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteInviteKey
     * Summary: 無効化する
     * Notes: 指定の招待キーを無効化する。  なお、この操作はキーが有効な間だけ行える。  指定のWorkGroupへのADMIN権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $inviteKeyId InviteKeyのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteInviteKey(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $inviteKeyId
    ): ResponseInterface {
        $message = "How about implementing deleteInviteKey as a DELETE method in dev_t0r\trvis_backend\api\InviteKeyApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getInviteKey
     * Summary: 1件取得する
     * Notes: 招待キーの情報を1件取得する  削除された招待キーは取得できませんが、無効化された招待キーは取得できます。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $inviteKeyId InviteKeyのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getInviteKey(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $inviteKeyId
    ): ResponseInterface {
        $message = "How about implementing getInviteKey as a GET method in dev_t0r\trvis_backend\api\InviteKeyApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getInviteKeyList
     * Summary: 一覧を取得する
     * Notes: 指定のWorkGroupに属する招待キーの一覧を取得する  指定のWorkGroupへのADMIN権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $workGroupId WorkGroupのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getInviteKeyList(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $workGroupId
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $p = (key_exists('p', $queryParams)) ? $queryParams['p'] : null;
        $limit = (key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $top = (key_exists('top', $queryParams)) ? $queryParams['top'] : null;
        $expired = (key_exists('expired', $queryParams)) ? $queryParams['expired'] : null;
        $message = "How about implementing getInviteKeyList as a GET method in dev_t0r\trvis_backend\api\InviteKeyApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getMyInviteKeyList
     * Summary: 一覧を取得する
     * Notes: 自身が作成した (オーナーな) 招待キーの一覧を取得する  実行にはサインインが必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getMyInviteKeyList(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $p = (key_exists('p', $queryParams)) ? $queryParams['p'] : null;
        $limit = (key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $top = (key_exists('top', $queryParams)) ? $queryParams['top'] : null;
        $expired = (key_exists('expired', $queryParams)) ? $queryParams['expired'] : null;
        $message = "How about implementing getMyInviteKeyList as a GET method in dev_t0r\trvis_backend\api\InviteKeyApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT updateInviteKey
     * Summary: (未実装) 更新する
     * Notes: 既存の招待キーを更新する  指定のWorkGroupへのADMIN権限が必要です。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $inviteKeyId InviteKeyのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateInviteKey(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $inviteKeyId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing updateInviteKey as a PUT method in dev_t0r\trvis_backend\api\InviteKeyApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST useInviteKey
     * Summary: 使用する
     * Notes: 招待キーを使用する  サインインが必須です。サインインしたユーザに対して、この招待キーに割り当てられた権限が付与されます。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $inviteKeyId InviteKeyのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function useInviteKey(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $inviteKeyId
    ): ResponseInterface {
        $message = "How about implementing useInviteKey as a POST method in dev_t0r\trvis_backend\api\InviteKeyApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
