<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace dev_t0r\trvis_backend\api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractTrainApi Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractTrainApi
{
    /**
     * POST createTrain
     * Summary: 作成する
     * Notes: 指定のWorkに属する Train (列車) を新しく作成する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $workGroupId WorkGroupのID
     * @param string $workId WorkのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function createTrain(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $workGroupId,
        string $workId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing createTrain as a POST method in dev_t0r\trvis_backend\api\TrainApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteTrain
     * Summary: 削除する
     * Notes: 既存のTrainを削除する  なお、この操作はこのTrainのOwner、またはこのTrainが属するWorkまたはWorkGroupのOwnerのみが実行可能である。
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $workGroupId WorkGroupのID
     * @param string $workId WorkのID
     * @param string $trainId TrainのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteTrain(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $workGroupId,
        string $workId,
        string $trainId
    ): ResponseInterface {
        $message = "How about implementing deleteTrain as a DELETE method in dev_t0r\trvis_backend\api\TrainApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getTrain
     * Summary: 1件取得する
     * Notes: Train (列車) の情報を1件取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $workGroupId WorkGroupのID
     * @param string $workId WorkのID
     * @param string $trainId TrainのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getTrain(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $workGroupId,
        string $workId,
        string $trainId
    ): ResponseInterface {
        $message = "How about implementing getTrain as a GET method in dev_t0r\trvis_backend\api\TrainApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getTrainList
     * Summary: 複数件取得する
     * Notes: 指定のWorkに属するTrain (列車) の情報を複数件取得する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $workGroupId WorkGroupのID
     * @param string $workId WorkのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getTrainList(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $workGroupId,
        string $workId
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $p = (key_exists('p', $queryParams)) ? $queryParams['p'] : null;
        $limit = (key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = "How about implementing getTrainList as a GET method in dev_t0r\trvis_backend\api\TrainApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT updateTrain
     * Summary: 更新する
     * Notes: 既存のTrainの情報を更新する
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string $workGroupId WorkGroupのID
     * @param string $workId WorkのID
     * @param string $trainId TrainのID
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateTrain(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $workGroupId,
        string $workId,
        string $trainId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = "How about implementing updateTrain as a PUT method in dev_t0r\trvis_backend\api\TrainApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
