version: "3.8"
services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webmon-php
    hostname: webmon-php
    ports:
      - "80:80"
    volumes:
      - type: bind
        read_only: true
        source: ./backend
        target: /var/www/html
      - type: bind
        source: ./backend-logs
        target: /var/log/apache2
  mysql:
    image: mysql:8.0-oracle
    container_name: webmon-db
    hostname: webmon-db
    volumes:
      - type: bind
        read_only: true
        source: ./mysql/init_sql
        target: /docker-entrypoint-initdb.d
      - type: bind
        read_only: true
        source: ./mysql/conf.d
        target: /etc/mysql/conf.d
      - type: bind
        source: ./mysql/logs
        target: /var/log/mysql
      - type: volume
        source: webmon-db
        target: /var/lib/mysql
    env_file:
      - mysql/.env
    ports:
      - "3306:3306"
volumes:
  webmon-db:

