version: "3.8"
services:
  proxy:
    image: nginx:1.25.3-alpine-slim
    container_name: webmon-proxy
    hostname: webmon-proxy
    ports:
      - "80:80"
    networks:
      - proxy-front
      - proxy-back
    volumes:
      - type: bind
        read_only: true
        source: ./proxy/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./proxy/logs
        target: /var/log/nginx
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webmon-front
    hostname: webmon-front
    networks:
      - proxy-front
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webmon-php
    hostname: webmon-php
    networks:
      - back-db
      - proxy-back
    ports:
      - "8080:80"
    volumes:
      - type: bind
        read_only: true
        source: ./backend
        target: /var/www/html
      - type: bind
        source: ./backend-logs
        target: /var/log/apache2
      - type: bind
        read_only: true
        source: ./my_apache2.conf
        target: /etc/apache2/mods-enabled/my_apache2.conf
  firebase:
    build:
      context: ./firebase
      dockerfile: Dockerfile
    container_name: webmon-firebase
    hostname: webmon-firebase
    ports:
      - "9099:9099"
      - "4000:4000"
    volumes:
      - type: bind
        source: ./firebase/data
        target: /emulator/data
  mysql:
    image: mysql:5.7-oracle
    platform: linux/amd64
    container_name: webmon-db
    hostname: webmon-db
    networks:
      - back-db
    volumes:
      - type: bind
        read_only: true
        source: ./mysql/init_sql
        target: /docker-entrypoint-initdb.d
      - type: bind
        read_only: true
        source: ./mysql/conf.d
        target: /etc/mysql/conf.d
      - type: bind
        source: ./mysql/logs
        target: /var/log/mysql
      - type: volume
        source: webmon-db
        target: /var/lib/mysql
    env_file:
      - mysql/.env
volumes:
  webmon-db:
networks:
  proxy-front:
  proxy-back:
  back-db:
