<?php

namespace dev_t0r\trvis_backend;

use Ramsey\Uuid\Uuid;

final class Constants
{
	const HTTP_OK = 200;
	const HTTP_CREATED = 201;
	const HTTP_ACCEPTED = 202;
	const HTTP_NO_CONTENT = 204;

	const HTTP_MOVED_PERMANENTLY = 301;
	const HTTP_FOUND = 302;
	const HTTP_NOT_MODIFIED = 304;

	const HTTP_BAD_REQUEST = 400;
	const HTTP_UNAUTHORIZED = 401;
	const HTTP_FORBIDDEN = 403;
	const HTTP_NOT_FOUND = 404;
	const HTTP_METHOD_NOT_ALLOWED = 405;
	const HTTP_NOT_ACCEPTABLE = 406;
	const HTTP_CONFLICT = 409;
	const HTTP_PRECONDITION_FAILED = 412;
	const HTTP_UNSUPPORTED_MEDIA_TYPE = 415;

	const HTTP_INTERNAL_SERVER_ERROR = 500;
	const HTTP_NOT_IMPLEMENTED = 501;
	const HTTP_BAD_GATEWAY = 502;
	const HTTP_SERVICE_UNAVAILABLE = 503;
	const HTTP_GATEWAY_TIMEOUT = 504;
	const HTTP_VERSION_NOT_SUPPORTED = 505;

	const UUID_NULL = new Uuid(Uuid::NIL);
	const UID_ANONUMOUS = '';
}
