<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * ColorReal
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class ColorReal extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "ColorReal",
  "required" : [ "blue_real", "green_real", "red_real" ],
  "type" : "object",
  "properties" : {
    "red" : {
      "maximum" : 1,
      "minimum" : 0,
      "type" : "number",
      "description" : "色の赤色成分 (小数)",
      "format" : "double",
      "example" : 0.5
    },
    "green" : {
      "maximum" : 1,
      "minimum" : 0,
      "type" : "number",
      "description" : "色の緑色成分 (小数)",
      "format" : "double",
      "example" : 0.5
    },
    "blue" : {
      "maximum" : 1,
      "minimum" : 0,
      "type" : "number",
      "description" : "色の青色成分 (小数)",
      "format" : "double",
      "example" : 0.5
    }
  }
}
SCHEMA;
}
