<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * InviteKey
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InviteKey extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "InviteKey",
  "required" : [ "description" ],
  "type" : "object",
  "properties" : {
    "invite_keys_id" : {
      "type" : "string",
      "description" : "Invite Key (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時",
      "format" : "date-time",
      "readOnly" : true
    },
    "description" : {
      "type" : "string",
      "description" : "招待キーの説明",
      "example" : "グループAの招待キー"
    },
    "valid_from" : {
      "type" : "string",
      "description" : "キーの有効期限 (開始)",
      "format" : "date-time"
    },
    "expires_at" : {
      "type" : "string",
      "description" : "キーの有効期限 (終了)",
      "format" : "date-time"
    },
    "use_limit" : {
      "minimum" : 1,
      "type" : "integer",
      "description" : "キーの使用回数の上限",
      "example" : 15
    },
    "disabled_at" : {
      "type" : "string",
      "description" : "キーが無効になった日時 (Expireした場合はexpires_atと同じ値)",
      "format" : "date-time",
      "readOnly" : true
    },
    "privilege_type" : {
      "type" : "string",
      "description" : "招待キーで付与される権限",
      "example" : "read",
      "enum" : [ "read", "write", "admin" ]
    }
  }
}
SCHEMA;
}
