<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * ProjectStation
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class ProjectStation extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "ProjectStation",
  "required" : [ "name" ],
  "type" : "object",
  "properties" : {
    "project_stations_id" : {
      "type" : "string",
      "description" : "Project Station (Project内共通の駅) のID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "projects_id" : {
      "type" : "string",
      "description" : "ProjectのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時",
      "format" : "date-time",
      "readOnly" : true
    },
    "name" : {
      "type" : "string",
      "description" : "駅名",
      "example" : "東京"
    },
    "full_name" : {
      "type" : "string",
      "description" : "駅のフルネーム",
      "example" : "東京駅"
    },
    "location_lonlat" : {
      "$ref" : "#/components/schemas/ProjectStation_location_lonlat"
    },
    "on_station_detect_radius_m" : {
      "type" : "number",
      "description" : "その駅にいるかどうかを判定する円の半径 (m)",
      "format" : "double",
      "example" : 123.45
    },
    "always_show_hh" : {
      "type" : "boolean",
      "description" : "時刻表示で常に「時」を表示するかどうか",
      "example" : false
    }
  }
}
SCHEMA;
}
