<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * StationTrack
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class StationTrack extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "StationTrack",
  "required" : [ "description", "name" ],
  "type" : "object",
  "properties" : {
    "station_tracks_id" : {
      "type" : "string",
      "description" : "Station TrackのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "stations_id" : {
      "type" : "string",
      "description" : "StationのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時",
      "format" : "date-time",
      "readOnly" : true
    },
    "description" : {
      "type" : "string",
      "description" : "Station Trackの説明",
      "example" : "Station Trackの説明が入ります"
    },
    "name" : {
      "type" : "string",
      "description" : "その番線の名前",
      "example" : "上2"
    },
    "run_in_limit" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "進入制限のデフォルト値 (km/h)",
      "example" : 15
    },
    "run_out_limit" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "進出制限のデフォルト値 (km/h)",
      "example" : 15
    }
  }
}
SCHEMA;
}
