<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * Station
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Station extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "Station",
  "required" : [ "description", "location_km", "name", "record_type" ],
  "type" : "object",
  "properties" : {
    "stations_id" : {
      "type" : "string",
      "description" : "StationのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "work_groups_id" : {
      "type" : "string",
      "description" : "WorkGroupのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時",
      "format" : "date-time",
      "readOnly" : true
    },
    "description" : {
      "type" : "string",
      "description" : "Stationの説明",
      "example" : "Stationの説明が入ります"
    },
    "name" : {
      "type" : "string",
      "description" : "駅名",
      "example" : "東京"
    },
    "location_km" : {
      "type" : "number",
      "description" : "駅の位置 (km)",
      "format" : "double",
      "example" : 12.345
    },
    "location_lonlat" : {
      "$ref" : "#/components/schemas/Station_location_lonlat"
    },
    "on_station_detect_radius_m" : {
      "type" : "number",
      "description" : "その駅にいるかどうかを判定する円の半径 (m)",
      "format" : "double",
      "example" : 123.45
    },
    "record_type" : {
      "type" : "number",
      "description" : "駅の種類",
      "example" : 0
    }
  }
}
SCHEMA;
}
