<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * StopPattern
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class StopPattern extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "StopPattern",
  "required" : [ "lines_id", "name" ],
  "type" : "object",
  "properties" : {
    "stop_patterns_id" : {
      "type" : "string",
      "description" : "StopPatternのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "projects_id" : {
      "type" : "string",
      "description" : "ProjectのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "lines_id" : {
      "type" : "string",
      "description" : "紐づくLineのID (UUID)",
      "format" : "uuid"
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時",
      "format" : "date-time",
      "readOnly" : true
    },
    "name" : {
      "type" : "string",
      "description" : "停車パターンの名前",
      "example" : "各駅停車"
    },
    "from_project_stations_id" : {
      "type" : "string",
      "description" : "始点のProject StationのID (UUID)",
      "format" : "uuid"
    },
    "to_project_stations_id" : {
      "type" : "string",
      "description" : "終点のProject StationのID (UUID)",
      "format" : "uuid"
    },
    "direction" : {
      "type" : "integer",
      "description" : "進行方向 (1=下り, -1=上り)",
      "example" : 1,
      "enum" : [ 1, -1 ]
    }
  }
}
SCHEMA;
}
