<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * StopPatternRow
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class StopPatternRow extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "StopPatternRow",
  "required" : [ "project_stations_id" ],
  "type" : "object",
  "properties" : {
    "stop_pattern_rows_id" : {
      "type" : "string",
      "description" : "StopPatternRowのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "stop_patterns_id" : {
      "type" : "string",
      "description" : "紐づくStopPatternのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "projects_id" : {
      "type" : "string",
      "description" : "ProjectのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "project_stations_id" : {
      "type" : "string",
      "description" : "この行の駅 (Project Station) のID (UUID)",
      "format" : "uuid"
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時",
      "format" : "date-time",
      "readOnly" : true
    },
    "sort_key" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "並び順 (昇順)",
      "example" : 0
    },
    "track_name" : {
      "type" : "string",
      "description" : "番線名",
      "example" : "上2"
    },
    "track_hidden" : {
      "type" : "boolean",
      "description" : "番線を非表示にするかどうか",
      "example" : false
    },
    "is_operation_only_stop" : {
      "type" : "boolean",
      "description" : "運転停車かどうか",
      "example" : false
    },
    "is_pass" : {
      "type" : "boolean",
      "description" : "通過駅かどうか",
      "example" : false
    },
    "drive_time_mm" : {
      "maximum" : 99,
      "minimum" : 0,
      "type" : "integer",
      "description" : "駅間運転時間 (分)",
      "example" : 3
    },
    "drive_time_ss" : {
      "maximum" : 59,
      "minimum" : 0,
      "type" : "integer",
      "description" : "駅間運転時間 (秒)",
      "example" : 15
    },
    "dwell_time_mm" : {
      "maximum" : 99,
      "minimum" : 0,
      "type" : "integer",
      "description" : "停車時間 (分)",
      "example" : 1
    },
    "dwell_time_ss" : {
      "maximum" : 59,
      "minimum" : 0,
      "type" : "integer",
      "description" : "停車時間 (秒)",
      "example" : 0
    },
    "show_arrive" : {
      "type" : "boolean",
      "description" : "到着時刻を表示するかどうか",
      "example" : true
    },
    "show_departure" : {
      "type" : "boolean",
      "description" : "出発時刻を表示するかどうか",
      "example" : true
    },
    "arrive_str" : {
      "type" : "string",
      "description" : "到着時刻欄に表示する文字列",
      "example" : "停車"
    },
    "departure_str" : {
      "type" : "string",
      "description" : "出発時刻欄に表示する文字列",
      "example" : "↓"
    },
    "run_in_limit" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "進入制限 (km/h)",
      "example" : 15
    },
    "run_out_limit" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "進出制限 (km/h)",
      "example" : 15
    },
    "remarks" : {
      "type" : "string",
      "description" : "注意事項",
      "example" : "通過設定"
    },
    "always_show_hh" : {
      "type" : "boolean",
      "description" : "時刻表示で常に「時」を表示するかどうか",
      "example" : false
    }
  }
}
SCHEMA;
}
