<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * TimetableRow
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TimetableRow extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "TimetableRow",
  "type" : "object",
  "properties" : {
    "timetable_rows_id" : {
      "type" : "string",
      "description" : "TimetableRowのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "trains_id" : {
      "type" : "string",
      "description" : "このデータが紐づいているTrainのID (UUID)",
      "format" : "uuid",
      "readOnly" : true
    },
    "stations_id" : {
      "type" : "string",
      "description" : "この行の駅のID (UUID)",
      "format" : "uuid"
    },
    "station_tracks_id" : {
      "type" : "string",
      "description" : "駅の番線情報のID (UUID)",
      "format" : "uuid"
    },
    "colors_id_marker" : {
      "type" : "string",
      "description" : "マーカーの色情報のID (UUID)",
      "format" : "uuid"
    },
    "description" : {
      "type" : "string",
      "description" : "このTimetableRowの説明",
      "example" : "このTimetableRowの説明が入ります"
    },
    "created_at" : {
      "type" : "string",
      "description" : "作成日時",
      "format" : "date-time",
      "readOnly" : true
    },
    "updated_at" : {
      "type" : "string",
      "description" : "更新日時",
      "format" : "date-time",
      "readOnly" : true
    },
    "drive_time_mm" : {
      "maximum" : 99,
      "minimum" : 0,
      "type" : "integer",
      "description" : "駅間運転時間 (分)",
      "example" : 3
    },
    "drive_time_ss" : {
      "maximum" : 59,
      "minimum" : 0,
      "type" : "integer",
      "description" : "駅間運転時間 (秒)",
      "example" : 15
    },
    "is_operation_only_stop" : {
      "type" : "boolean",
      "description" : "運転停車かどうか",
      "example" : false
    },
    "is_pass" : {
      "type" : "boolean",
      "description" : "通過駅かどうか",
      "example" : false
    },
    "has_bracket" : {
      "type" : "boolean",
      "description" : "到着時刻に括弧を付けるかどうか",
      "example" : false
    },
    "is_last_stop" : {
      "type" : "boolean",
      "description" : "終着駅かどうか",
      "example" : false
    },
    "arrive_time_hh" : {
      "maximum" : 23,
      "minimum" : 0,
      "type" : "integer",
      "description" : "到着時刻 (時)",
      "example" : 15
    },
    "arrive_time_mm" : {
      "maximum" : 59,
      "minimum" : 0,
      "type" : "integer",
      "description" : "到着時刻 (分)",
      "example" : 20
    },
    "arrive_time_ss" : {
      "maximum" : 59,
      "minimum" : 0,
      "type" : "integer",
      "description" : "到着時刻 (秒)",
      "example" : 25
    },
    "departure_time_hh" : {
      "maximum" : 23,
      "minimum" : 0,
      "type" : "integer",
      "description" : "出発時刻 (時)",
      "example" : 15
    },
    "departure_time_mm" : {
      "maximum" : 59,
      "minimum" : 0,
      "type" : "integer",
      "description" : "出発時刻 (分)",
      "example" : 20
    },
    "departure_time_ss" : {
      "maximum" : 59,
      "minimum" : 0,
      "type" : "integer",
      "description" : "出発時刻 (秒)",
      "example" : 25
    },
    "run_in_limit" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "進入制限 (km/h)",
      "example" : 15
    },
    "run_out_limit" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "進出制限 (km/h)",
      "example" : 15
    },
    "remarks" : {
      "type" : "string",
      "description" : "注意事項",
      "example" : "通過設定"
    },
    "arrive_str" : {
      "type" : "string",
      "description" : "到着時刻欄に表示する文字列",
      "example" : "停車"
    },
    "departure_str" : {
      "type" : "string",
      "description" : "出発時刻欄に表示する文字列",
      "example" : "???"
    },
    "marker_text" : {
      "type" : "string",
      "description" : "マーカー部分に表示する文字列",
      "example" : "合図"
    },
    "work_type" : {
      "type" : "string",
      "description" : "作業種別 (実装準備中)"
    }
  }
}
SCHEMA;
}
