<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace dev_t0r\trvis_backend\model;

use dev_t0r\BaseModel;

/**
 * TRViSJsonTrain
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TRViSJsonTrain extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\dev_t0r\trvis_backend\model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "TRViS_Train",
  "required" : [ "Direction", "TimetableRows", "TrainNumber" ],
  "type" : "object",
  "properties" : {
    "TrainNumber" : {
      "type" : "string",
      "description" : "列車番号",
      "example" : "試1234M"
    },
    "MaxSpeed" : {
      "type" : "string",
      "description" : "最高速度",
      "nullable" : true,
      "example" : "110"
    },
    "SpeedType" : {
      "type" : "string",
      "description" : "速度種別",
      "nullable" : true,
      "example" : "通電A20"
    },
    "NominalTractiveCapacity" : {
      "type" : "string",
      "description" : "けん引定数",
      "nullable" : true,
      "example" : "XXX系 1M9T"
    },
    "CarCount" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "車両数",
      "nullable" : true,
      "example" : 10
    },
    "Destination" : {
      "type" : "string",
      "description" : "行先",
      "nullable" : true,
      "example" : "東  京"
    },
    "BeginRemarks" : {
      "type" : "string",
      "description" : "乗車前の注意事項 (「乗継」など)",
      "nullable" : true,
      "example" : "(乗継)"
    },
    "AfterRemarks" : {
      "type" : "string",
      "description" : "降車後の注意事項 (「乗継」など)",
      "nullable" : true,
      "example" : "(乗継)"
    },
    "Remarks" : {
      "type" : "string",
      "description" : "注意事項",
      "nullable" : true,
      "example" : "XXXX ~ YYYY 徐行 30km/h\nAAAA ~ BBBB 車掌省略\n"
    },
    "BeforeDeparture" : {
      "type" : "string",
      "description" : "発前",
      "nullable" : true,
      "example" : "転線 5分          転線"
    },
    "TrainInfo" : {
      "type" : "string",
      "description" : "列車に関する情報",
      "nullable" : true,
      "example" : "<div style=\"color: red\">車掌省略</div>"
    },
    "Direction" : {
      "type" : "integer",
      "description" : "進行方向 (0~1: 下り, -1: 上り)",
      "example" : 1
    },
    "AfterArrive" : {
      "type" : "string",
      "description" : "発前",
      "nullable" : true,
      "example" : "転線 5分          転線"
    },
    "DayCount" : {
      "minimum" : 0,
      "type" : "integer",
      "description" : "仕業の初日からの経過日数 (0で初日/日勤、1で明け)",
      "example" : 1
    },
    "IsRideOnMoving" : {
      "type" : "boolean",
      "description" : "添乗での移動かどうか",
      "example" : false
    },
    "TimetableRows" : {
      "type" : "array",
      "description" : "このTrainに属するTimetableRowの配列",
      "items" : {
        "$ref" : "#/components/schemas/TRViS_json_TimetableRow"
      }
    }
  }
}
SCHEMA;
}
