openapi: 3.0.3

info:
  title: TRViS用 時刻表管理用API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: ローカル開発環境
  - url: https://trvis.t0r.dev
    description: 本番環境

tags:
  - name: api_info
    description: APIの情報を取得する
  - name: auth
    description: 認証/認可関連のAPI (トークン発行など)
  - name: work_group
    description: Work Groupの操作を行う
  - name: station
    description: Stationの操作を行う
  - name: station_track
    description: Station Track (各駅の番線) の操作を行う
  - name: work
    description: Work (仕業) の操作を行う
  - name: train
    description: Train (列車) の操作を行う

paths:
  /api/v1/api_info:
    $ref: "./paths/api_info/index.yaml#/path"

  /api/v1/auths:
    $ref: "./paths/auth/index.yaml#/path"

  /api/v1/work_groups:
    $ref: "./paths/work_groups/index.yaml#/path"
  /api/v1/work_groups/{work_group_id}:
    $ref: "./paths/work_groups/id.yaml#/path"

  /api/v1/work_groups/{work_group_id}/stations:
    $ref: "./paths/stations/index.yaml#/path"
  /api/v1/work_groups/{work_group_id}/stations/{station_id}:
    $ref: "./paths/stations/id.yaml#/path"

  /api/v1/work_groups/{work_group_id}/stations/{station_id}/tracks:
    $ref: "./paths/station_tracks/index.yaml#/path"
  /api/v1/work_groups/{work_group_id}/stations/{station_id}/tracks/{station_track_id}:
    $ref: "./paths/station_tracks/id.yaml#/path"

  /api/v1/work_groups/{work_group_id}/works:
    $ref: "./paths/works/index.yaml#/path"
  /api/v1/work_groups/{work_group_id}/works/{work_id}:
    $ref: "./paths/works/id.yaml#/path"
  # 将来的には対応させたい
  # /api/v1/works/{id}:
  #   $ref: "./paths/works/id.yaml#/path"

  /api/v1/work_groups/{work_group_id}/works/{work_id}/trains:
    $ref: "./paths/trains/index.yaml#/path"
  /api/v1/work_groups/{work_group_id}/works/{work_id}/trains/{train_id}:
    $ref: "./paths/trains/id.yaml#/path"
  # 将来的には対応させたい
  # /api/v1/trains/{id}:
  #   $ref: "./paths/trains/id.yaml#/path"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
