<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\trvis_backend\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\api\ColorApi;

/**
 * ColorApiTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\api\ColorApi
 */
class ColorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createColor
     *
     * 作成する.
     *
     * @covers ::createColor
     */
    public function testCreateColor()
    {
        $this->markTestIncomplete(
            'Test of "createColor" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteColor
     *
     * 削除する.
     *
     * @covers ::deleteColor
     */
    public function testDeleteColor()
    {
        $this->markTestIncomplete(
            'Test of "deleteColor" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getColor
     *
     * 1件取得する.
     *
     * @covers ::getColor
     */
    public function testGetColor()
    {
        $this->markTestIncomplete(
            'Test of "getColor" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getColorList
     *
     * 複数件取得する.
     *
     * @covers ::getColorList
     */
    public function testGetColorList()
    {
        $this->markTestIncomplete(
            'Test of "getColorList" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateColor
     *
     * 更新する.
     *
     * @covers ::updateColor
     */
    public function testUpdateColor()
    {
        $this->markTestIncomplete(
            'Test of "updateColor" method has not been implemented yet.'
        );
    }
}
