<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\trvis_backend\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\api\StationTrackApi;

/**
 * StationTrackApiTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\api\StationTrackApi
 */
class StationTrackApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createStationTrack
     *
     * 作成する.
     *
     * @covers ::createStationTrack
     */
    public function testCreateStationTrack()
    {
        $this->markTestIncomplete(
            'Test of "createStationTrack" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteStationTrack
     *
     * 削除する.
     *
     * @covers ::deleteStationTrack
     */
    public function testDeleteStationTrack()
    {
        $this->markTestIncomplete(
            'Test of "deleteStationTrack" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getStationTrack
     *
     * 1件取得する.
     *
     * @covers ::getStationTrack
     */
    public function testGetStationTrack()
    {
        $this->markTestIncomplete(
            'Test of "getStationTrack" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getStationTrackList
     *
     * 複数件取得する.
     *
     * @covers ::getStationTrackList
     */
    public function testGetStationTrackList()
    {
        $this->markTestIncomplete(
            'Test of "getStationTrackList" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateStationTrack
     *
     * 更新する.
     *
     * @covers ::updateStationTrack
     */
    public function testUpdateStationTrack()
    {
        $this->markTestIncomplete(
            'Test of "updateStationTrack" method has not been implemented yet.'
        );
    }
}
