<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\trvis_backend\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\api\StationApi;

/**
 * StationApiTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\api\StationApi
 */
class StationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createStation
     *
     * 作成する.
     *
     * @covers ::createStation
     */
    public function testCreateStation()
    {
        $this->markTestIncomplete(
            'Test of "createStation" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteStation
     *
     * 削除する.
     *
     * @covers ::deleteStation
     */
    public function testDeleteStation()
    {
        $this->markTestIncomplete(
            'Test of "deleteStation" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getStation
     *
     * 1件取得する.
     *
     * @covers ::getStation
     */
    public function testGetStation()
    {
        $this->markTestIncomplete(
            'Test of "getStation" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getStationList
     *
     * 複数件取得する.
     *
     * @covers ::getStationList
     */
    public function testGetStationList()
    {
        $this->markTestIncomplete(
            'Test of "getStationList" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateStation
     *
     * 更新する.
     *
     * @covers ::updateStation
     */
    public function testUpdateStation()
    {
        $this->markTestIncomplete(
            'Test of "updateStation" method has not been implemented yet.'
        );
    }
}
