<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\trvis_backend\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\api\StopPatternApi;

/**
 * StopPatternApiTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\api\StopPatternApi
 */
class StopPatternApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createStopPattern
     *
     * 作成する.
     *
     * @covers ::createStopPattern
     */
    public function testCreateStopPattern()
    {
        $this->markTestIncomplete(
            'Test of "createStopPattern" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteStopPattern
     *
     * 削除する.
     *
     * @covers ::deleteStopPattern
     */
    public function testDeleteStopPattern()
    {
        $this->markTestIncomplete(
            'Test of "deleteStopPattern" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getStopPattern
     *
     * 1件取得する.
     *
     * @covers ::getStopPattern
     */
    public function testGetStopPattern()
    {
        $this->markTestIncomplete(
            'Test of "getStopPattern" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getStopPatternList
     *
     * 複数件取得する.
     *
     * @covers ::getStopPatternList
     */
    public function testGetStopPatternList()
    {
        $this->markTestIncomplete(
            'Test of "getStopPatternList" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateStopPattern
     *
     * 更新する.
     *
     * @covers ::updateStopPattern
     */
    public function testUpdateStopPattern()
    {
        $this->markTestIncomplete(
            'Test of "updateStopPattern" method has not been implemented yet.'
        );
    }
}
