<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\trvis_backend\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\api\TimetableRowApi;

/**
 * TimetableRowApiTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\api\TimetableRowApi
 */
class TimetableRowApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTimetableRow
     *
     * 作成する.
     *
     * @covers ::createTimetableRow
     */
    public function testCreateTimetableRow()
    {
        $this->markTestIncomplete(
            'Test of "createTimetableRow" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteTimetableRow
     *
     * 削除する.
     *
     * @covers ::deleteTimetableRow
     */
    public function testDeleteTimetableRow()
    {
        $this->markTestIncomplete(
            'Test of "deleteTimetableRow" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getTimetableRow
     *
     * 1件取得する.
     *
     * @covers ::getTimetableRow
     */
    public function testGetTimetableRow()
    {
        $this->markTestIncomplete(
            'Test of "getTimetableRow" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getTimetableRowList
     *
     * 複数件取得する.
     *
     * @covers ::getTimetableRowList
     */
    public function testGetTimetableRowList()
    {
        $this->markTestIncomplete(
            'Test of "getTimetableRowList" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateTimetableRow
     *
     * 更新する.
     *
     * @covers ::updateTimetableRow
     */
    public function testUpdateTimetableRow()
    {
        $this->markTestIncomplete(
            'Test of "updateTimetableRow" method has not been implemented yet.'
        );
    }
}
