<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\trvis_backend\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\api\WorkGroupApi;

/**
 * WorkGroupApiTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\api\WorkGroupApi
 */
class WorkGroupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWorkGroup
     *
     * 作成する.
     *
     * @covers ::createWorkGroup
     */
    public function testCreateWorkGroup()
    {
        $this->markTestIncomplete(
            'Test of "createWorkGroup" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteWorkGroup
     *
     * 削除する.
     *
     * @covers ::deleteWorkGroup
     */
    public function testDeleteWorkGroup()
    {
        $this->markTestIncomplete(
            'Test of "deleteWorkGroup" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getWorkGroup
     *
     * 1件取得する.
     *
     * @covers ::getWorkGroup
     */
    public function testGetWorkGroup()
    {
        $this->markTestIncomplete(
            'Test of "getWorkGroup" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getWorkGroupList
     *
     * 複数件取得する.
     *
     * @covers ::getWorkGroupList
     */
    public function testGetWorkGroupList()
    {
        $this->markTestIncomplete(
            'Test of "getWorkGroupList" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateWorkGroup
     *
     * 更新する.
     *
     * @covers ::updateWorkGroup
     */
    public function testUpdateWorkGroup()
    {
        $this->markTestIncomplete(
            'Test of "updateWorkGroup" method has not been implemented yet.'
        );
    }
}
