<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace dev_t0r\trvis_backend\api;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\api\WorkApi;

/**
 * WorkApiTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\api\WorkApi
 */
class WorkApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWork
     *
     * 作成する.
     *
     * @covers ::createWork
     */
    public function testCreateWork()
    {
        $this->markTestIncomplete(
            'Test of "createWork" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteWork
     *
     * 削除する.
     *
     * @covers ::deleteWork
     */
    public function testDeleteWork()
    {
        $this->markTestIncomplete(
            'Test of "deleteWork" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getWork
     *
     * 1件取得する.
     *
     * @covers ::getWork
     */
    public function testGetWork()
    {
        $this->markTestIncomplete(
            'Test of "getWork" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getWorkList
     *
     * 複数件取得する.
     *
     * @covers ::getWorkList
     */
    public function testGetWorkList()
    {
        $this->markTestIncomplete(
            'Test of "getWorkList" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateWork
     *
     * 更新する.
     *
     * @covers ::updateWork
     */
    public function testUpdateWork()
    {
        $this->markTestIncomplete(
            'Test of "updateWork" method has not been implemented yet.'
        );
    }
}
