/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Color8bit
 */
export interface Color8bit {
    /**
     * 色の赤色成分 (8bit)
     * @type {number}
     * @memberof Color8bit
     */
    red?: number;
    /**
     * 色の緑色成分 (8bit)
     * @type {number}
     * @memberof Color8bit
     */
    green?: number;
    /**
     * 色の青色成分 (8bit)
     * @type {number}
     * @memberof Color8bit
     */
    blue?: number;
}

/**
 * Check if a given object implements the Color8bit interface.
 */
export function instanceOfColor8bit(value: object): value is Color8bit {
    return true;
}

export function Color8bitFromJSON(json: any): Color8bit {
    return Color8bitFromJSONTyped(json, false);
}

export function Color8bitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Color8bit {
    if (json == null) {
        return json;
    }
    return {
        
        'red': json['red'] == null ? undefined : json['red'],
        'green': json['green'] == null ? undefined : json['green'],
        'blue': json['blue'] == null ? undefined : json['blue'],
    };
}

export function Color8bitToJSON(value?: Color8bit | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'red': value['red'],
        'green': value['green'],
        'blue': value['blue'],
    };
}

