/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteKey
 */
export interface InviteKey {
    /**
     * 招待キーの説明
     * @type {string}
     * @memberof InviteKey
     */
    description: string;
    /**
     * Invite Key (UUID)
     * @type {string}
     * @memberof InviteKey
     */
    readonly inviteKeysId?: string;
    /**
     * 対応するWorkGroupのID (UUID)
     * @type {string}
     * @memberof InviteKey
     */
    readonly workGroupsId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof InviteKey
     */
    readonly createdAt?: Date;
    /**
     * キーの有効期限 (開始)
     * @type {Date}
     * @memberof InviteKey
     */
    validFrom?: Date;
    /**
     * キーの有効期限 (終了)
     * @type {Date}
     * @memberof InviteKey
     */
    expiresAt?: Date;
    /**
     * キーの使用回数の上限
     * @type {number}
     * @memberof InviteKey
     */
    useLimit?: number;
    /**
     * キーが無効になった日時 (Expireした場合はexpires_atと同じ値)
     * @type {Date}
     * @memberof InviteKey
     */
    readonly disabledAt?: Date;
    /**
     * 招待キーで付与される権限
     * @type {string}
     * @memberof InviteKey
     */
    privilegeType?: InviteKeyPrivilegeTypeEnum;
}


/**
 * @export
 */
export const InviteKeyPrivilegeTypeEnum = {
    Read: 'read',
    Write: 'write',
    Admin: 'admin'
} as const;
export type InviteKeyPrivilegeTypeEnum = typeof InviteKeyPrivilegeTypeEnum[keyof typeof InviteKeyPrivilegeTypeEnum];


/**
 * Check if a given object implements the InviteKey interface.
 */
export function instanceOfInviteKey(value: object): value is InviteKey {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function InviteKeyFromJSON(json: any): InviteKey {
    return InviteKeyFromJSONTyped(json, false);
}

export function InviteKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteKey {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'inviteKeysId': json['invite_keys_id'] == null ? undefined : json['invite_keys_id'],
        'workGroupsId': json['work_groups_id'] == null ? undefined : json['work_groups_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'validFrom': json['valid_from'] == null ? undefined : (new Date(json['valid_from'])),
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'useLimit': json['use_limit'] == null ? undefined : json['use_limit'],
        'disabledAt': json['disabled_at'] == null ? undefined : (new Date(json['disabled_at'])),
        'privilegeType': json['privilege_type'] == null ? undefined : json['privilege_type'],
    };
}

export function InviteKeyToJSON(value?: Omit<InviteKey, 'invite_keys_id'|'work_groups_id'|'created_at'|'disabled_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'valid_from': value['validFrom'] == null ? undefined : ((value['validFrom']).toISOString()),
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
        'use_limit': value['useLimit'],
        'privilege_type': value['privilegeType'],
    };
}

