/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Line
 */
export interface Line {
    /**
     * Lineの説明
     * @type {string}
     * @memberof Line
     */
    description: string;
    /**
     * 路線名
     * @type {string}
     * @memberof Line
     */
    name: string;
    /**
     * LineのID (UUID)
     * @type {string}
     * @memberof Line
     */
    readonly linesId?: string;
    /**
     * ProjectのID (UUID)
     * @type {string}
     * @memberof Line
     */
    readonly projectsId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof Line
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the Line interface.
 */
export function instanceOfLine(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function LineFromJSON(json: any): Line {
    return LineFromJSONTyped(json, false);
}

export function LineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Line {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'name': json['name'],
        'linesId': !exists(json, 'lines_id') ? undefined : json['lines_id'],
        'projectsId': !exists(json, 'projects_id') ? undefined : json['projects_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function LineToJSON(value?: Line | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
    };
}

