/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 駅の位置 (緯度経度)
 * @export
 * @interface ProjectStationLocationLonlat
 */
export interface ProjectStationLocationLonlat {
    /**
     * 経度
     * @type {number}
     * @memberof ProjectStationLocationLonlat
     */
    longitude: number;
    /**
     * 緯度
     * @type {number}
     * @memberof ProjectStationLocationLonlat
     */
    latitude: number;
}

/**
 * Check if a given object implements the ProjectStationLocationLonlat interface.
 */
export function instanceOfProjectStationLocationLonlat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "latitude" in value;

    return isInstance;
}

export function ProjectStationLocationLonlatFromJSON(json: any): ProjectStationLocationLonlat {
    return ProjectStationLocationLonlatFromJSONTyped(json, false);
}

export function ProjectStationLocationLonlatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectStationLocationLonlat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'longitude': json['longitude'],
        'latitude': json['latitude'],
    };
}

export function ProjectStationLocationLonlatToJSON(value?: ProjectStationLocationLonlat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'longitude': value.longitude,
        'latitude': value.latitude,
    };
}

