/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsPrivilege
 */
export interface ProjectsPrivilege {
    /**
     * 権限の種類
     * @type {string}
     * @memberof ProjectsPrivilege
     */
    privilegeType: ProjectsPrivilegePrivilegeTypeEnum;
    /**
     * UserID
     * @type {string}
     * @memberof ProjectsPrivilege
     */
    readonly uid?: string;
    /**
     * ProjectのID (UUID)
     * @type {string}
     * @memberof ProjectsPrivilege
     */
    readonly projectsId?: string;
    /**
     * InviteKeyのID (UUID)
     * @type {string}
     * @memberof ProjectsPrivilege
     */
    readonly inviteKeysId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof ProjectsPrivilege
     */
    readonly createdAt?: Date;
    /**
     * 更新日時
     * @type {Date}
     * @memberof ProjectsPrivilege
     */
    readonly updatedAt?: Date;
}


/**
 * @export
 */
export const ProjectsPrivilegePrivilegeTypeEnum = {
    Read: 'read',
    Write: 'write',
    Admin: 'admin'
} as const;
export type ProjectsPrivilegePrivilegeTypeEnum = typeof ProjectsPrivilegePrivilegeTypeEnum[keyof typeof ProjectsPrivilegePrivilegeTypeEnum];


/**
 * Check if a given object implements the ProjectsPrivilege interface.
 */
export function instanceOfProjectsPrivilege(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "privilegeType" in value;

    return isInstance;
}

export function ProjectsPrivilegeFromJSON(json: any): ProjectsPrivilege {
    return ProjectsPrivilegeFromJSONTyped(json, false);
}

export function ProjectsPrivilegeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsPrivilege {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'privilegeType': json['privilege_type'],
        'uid': !exists(json, 'uid') ? undefined : json['uid'],
        'projectsId': !exists(json, 'projects_id') ? undefined : json['projects_id'],
        'inviteKeysId': !exists(json, 'invite_keys_id') ? undefined : json['invite_keys_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function ProjectsPrivilegeToJSON(value?: ProjectsPrivilege | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'privilege_type': value.privilegeType,
    };
}

