/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectStationLocationLonlat } from './ProjectStationLocationLonlat';
import {
    ProjectStationLocationLonlatFromJSON,
    ProjectStationLocationLonlatFromJSONTyped,
    ProjectStationLocationLonlatToJSON,
} from './ProjectStationLocationLonlat';

/**
 * 
 * @export
 * @interface ProjectStation
 */
export interface ProjectStation {
    /**
     * 駅名
     * @type {string}
     * @memberof ProjectStation
     */
    name: string;
    /**
     * Project Station (Project内共通の駅) のID (UUID)
     * @type {string}
     * @memberof ProjectStation
     */
    readonly projectStationsId?: string;
    /**
     * ProjectのID (UUID)
     * @type {string}
     * @memberof ProjectStation
     */
    readonly projectsId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof ProjectStation
     */
    readonly createdAt?: Date;
    /**
     * 駅のフルネーム
     * @type {string}
     * @memberof ProjectStation
     */
    fullName?: string;
    /**
     * 
     * @type {ProjectStationLocationLonlat}
     * @memberof ProjectStation
     */
    locationLonlat?: ProjectStationLocationLonlat;
    /**
     * その駅にいるかどうかを判定する円の半径 (m)
     * @type {number}
     * @memberof ProjectStation
     */
    onStationDetectRadiusM?: number;
    /**
     * 時刻表示で常に「時」を表示するかどうか
     * @type {boolean}
     * @memberof ProjectStation
     */
    alwaysShowHh?: boolean;
}

/**
 * Check if a given object implements the ProjectStation interface.
 */
export function instanceOfProjectStation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProjectStationFromJSON(json: any): ProjectStation {
    return ProjectStationFromJSONTyped(json, false);
}

export function ProjectStationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectStation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'projectStationsId': !exists(json, 'project_stations_id') ? undefined : json['project_stations_id'],
        'projectsId': !exists(json, 'projects_id') ? undefined : json['projects_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'locationLonlat': !exists(json, 'location_lonlat') ? undefined : ProjectStationLocationLonlatFromJSON(json['location_lonlat']),
        'onStationDetectRadiusM': !exists(json, 'on_station_detect_radius_m') ? undefined : json['on_station_detect_radius_m'],
        'alwaysShowHh': !exists(json, 'always_show_hh') ? undefined : json['always_show_hh'],
    };
}

export function ProjectStationToJSON(value?: ProjectStation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'full_name': value.fullName,
        'location_lonlat': ProjectStationLocationLonlatToJSON(value.locationLonlat),
        'on_station_detect_radius_m': value.onStationDetectRadiusM,
        'always_show_hh': value.alwaysShowHh,
    };
}

