/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * エラーコードとエラーメッセージ
 * @export
 * @interface Schema
 */
export interface Schema {
    /**
     * エラーコード
     * @type {number}
     * @memberof Schema
     */
    code?: number;
    /**
     * エラーメッセージ
     * @type {string}
     * @memberof Schema
     */
    message?: string;
}

/**
 * Check if a given object implements the Schema interface.
 */
export function instanceOfSchema(value: object): value is Schema {
    return true;
}

export function SchemaFromJSON(json: any): Schema {
    return SchemaFromJSONTyped(json, false);
}

export function SchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Schema {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SchemaToJSON(value?: Schema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

