/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StationTrack
 */
export interface StationTrack {
    /**
     * Station Trackの説明
     * @type {string}
     * @memberof StationTrack
     */
    description: string;
    /**
     * その番線の名前
     * @type {string}
     * @memberof StationTrack
     */
    name: string;
    /**
     * Station TrackのID (UUID)
     * @type {string}
     * @memberof StationTrack
     */
    readonly stationTracksId?: string;
    /**
     * StationのID (UUID)
     * @type {string}
     * @memberof StationTrack
     */
    readonly stationsId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof StationTrack
     */
    readonly createdAt?: Date;
    /**
     * 進入制限のデフォルト値 (km/h)
     * @type {number}
     * @memberof StationTrack
     */
    runInLimit?: number;
    /**
     * 進出制限のデフォルト値 (km/h)
     * @type {number}
     * @memberof StationTrack
     */
    runOutLimit?: number;
}

/**
 * Check if a given object implements the StationTrack interface.
 */
export function instanceOfStationTrack(value: object): value is StationTrack {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StationTrackFromJSON(json: any): StationTrack {
    return StationTrackFromJSONTyped(json, false);
}

export function StationTrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationTrack {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'name': json['name'],
        'stationTracksId': json['station_tracks_id'] == null ? undefined : json['station_tracks_id'],
        'stationsId': json['stations_id'] == null ? undefined : json['stations_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'runInLimit': json['run_in_limit'] == null ? undefined : json['run_in_limit'],
        'runOutLimit': json['run_out_limit'] == null ? undefined : json['run_out_limit'],
    };
}

export function StationTrackToJSON(value?: Omit<StationTrack, 'station_tracks_id'|'stations_id'|'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'name': value['name'],
        'run_in_limit': value['runInLimit'],
        'run_out_limit': value['runOutLimit'],
    };
}

