/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * その路線上での駅の位置 (緯度経度) ※未指定時はProject Stationの値を使用
 * @export
 * @interface StationOnLineLocationLonlat
 */
export interface StationOnLineLocationLonlat {
    /**
     * 経度
     * @type {number}
     * @memberof StationOnLineLocationLonlat
     */
    longitude: number;
    /**
     * 緯度
     * @type {number}
     * @memberof StationOnLineLocationLonlat
     */
    latitude: number;
}

/**
 * Check if a given object implements the StationOnLineLocationLonlat interface.
 */
export function instanceOfStationOnLineLocationLonlat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "latitude" in value;

    return isInstance;
}

export function StationOnLineLocationLonlatFromJSON(json: any): StationOnLineLocationLonlat {
    return StationOnLineLocationLonlatFromJSONTyped(json, false);
}

export function StationOnLineLocationLonlatFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationOnLineLocationLonlat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'longitude': json['longitude'],
        'latitude': json['latitude'],
    };
}

export function StationOnLineLocationLonlatToJSON(value?: StationOnLineLocationLonlat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'longitude': value.longitude,
        'latitude': value.latitude,
    };
}

