/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopPattern
 */
export interface StopPattern {
    /**
     * 紐づくLineのID (UUID)
     * @type {string}
     * @memberof StopPattern
     */
    linesId: string;
    /**
     * 停車パターンの名前
     * @type {string}
     * @memberof StopPattern
     */
    name: string;
    /**
     * StopPatternのID (UUID)
     * @type {string}
     * @memberof StopPattern
     */
    readonly stopPatternsId?: string;
    /**
     * ProjectのID (UUID)
     * @type {string}
     * @memberof StopPattern
     */
    readonly projectsId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof StopPattern
     */
    readonly createdAt?: Date;
    /**
     * 始点のProject StationのID (UUID)
     * @type {string}
     * @memberof StopPattern
     */
    fromProjectStationsId?: string;
    /**
     * 終点のProject StationのID (UUID)
     * @type {string}
     * @memberof StopPattern
     */
    toProjectStationsId?: string;
    /**
     * 進行方向 (1=下り, -1=上り)
     * @type {number}
     * @memberof StopPattern
     */
    direction?: StopPatternDirectionEnum;
}


/**
 * @export
 */
export const StopPatternDirectionEnum = {
    NUMBER_1: 1,
    NUMBER_MINUS_1: -1
} as const;
export type StopPatternDirectionEnum = typeof StopPatternDirectionEnum[keyof typeof StopPatternDirectionEnum];


/**
 * Check if a given object implements the StopPattern interface.
 */
export function instanceOfStopPattern(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "linesId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function StopPatternFromJSON(json: any): StopPattern {
    return StopPatternFromJSONTyped(json, false);
}

export function StopPatternFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopPattern {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'linesId': json['lines_id'],
        'name': json['name'],
        'stopPatternsId': !exists(json, 'stop_patterns_id') ? undefined : json['stop_patterns_id'],
        'projectsId': !exists(json, 'projects_id') ? undefined : json['projects_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'fromProjectStationsId': !exists(json, 'from_project_stations_id') ? undefined : json['from_project_stations_id'],
        'toProjectStationsId': !exists(json, 'to_project_stations_id') ? undefined : json['to_project_stations_id'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
    };
}

export function StopPatternToJSON(value?: StopPattern | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lines_id': value.linesId,
        'name': value.name,
        'from_project_stations_id': value.fromProjectStationsId,
        'to_project_stations_id': value.toProjectStationsId,
        'direction': value.direction,
    };
}

