/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * トークンの発行をリクエストする際に使用するオブジェクト
 * @export
 * @interface TokenRequest
 */
export interface TokenRequest {
    /**
     * APIキー
     * @type {string}
     * @memberof TokenRequest
     */
    apiKey: string;
    /**
     * APIキー
     * @type {string}
     * @memberof TokenRequest
     */
    clientId?: string;
}

/**
 * Check if a given object implements the TokenRequest interface.
 */
export function instanceOfTokenRequest(value: object): value is TokenRequest {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function TokenRequestFromJSON(json: any): TokenRequest {
    return TokenRequestFromJSONTyped(json, false);
}

export function TokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
    };
}

export function TokenRequestToJSON(value?: TokenRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'api_key': value['apiKey'],
        'client_id': value['clientId'],
    };
}

