/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TRViSJsonTrain } from './TRViSJsonTrain';
import {
    TRViSJsonTrainFromJSON,
    TRViSJsonTrainFromJSONTyped,
    TRViSJsonTrainToJSON,
} from './TRViSJsonTrain';

/**
 * 
 * @export
 * @interface TRViSJsonWork
 */
export interface TRViSJsonWork {
    /**
     * Workの名前
     * @type {string}
     * @memberof TRViSJsonWork
     */
    name: string;
    /**
     * このWorkに属するTrainの配列
     * @type {Array<TRViSJsonTrain>}
     * @memberof TRViSJsonWork
     */
    trains: Array<TRViSJsonTrain>;
    /**
     * この仕業の施行日
     * @type {Date}
     * @memberof TRViSJsonWork
     */
    affectDate?: Date | null;
    /**
     * AffixContentのContent-Type
     * @type {number}
     * @memberof TRViSJsonWork
     */
    affixContentType?: number | null;
    /**
     * 行路添付に表示する内容
     * @type {string}
     * @memberof TRViSJsonWork
     */
    affixContent?: string | null;
    /**
     * 仕業の注意事項に表示する内容
     * @type {string}
     * @memberof TRViSJsonWork
     */
    remarks?: string | null;
    /**
     * この行路にE電時刻表が存在するかどうか
     * @type {boolean}
     * @memberof TRViSJsonWork
     */
    hasETrainTimetable?: boolean;
    /**
     * E電時刻表のContent-Type
     * @type {number}
     * @memberof TRViSJsonWork
     */
    eTrainTimetableContentType?: number | null;
    /**
     * E電時刻表に表示する内容
     * @type {string}
     * @memberof TRViSJsonWork
     */
    eTrainTimetableContent?: string | null;
}

/**
 * Check if a given object implements the TRViSJsonWork interface.
 */
export function instanceOfTRViSJsonWork(value: object): value is TRViSJsonWork {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('trains' in value) || value['trains'] === undefined) return false;
    return true;
}

export function TRViSJsonWorkFromJSON(json: any): TRViSJsonWork {
    return TRViSJsonWorkFromJSONTyped(json, false);
}

export function TRViSJsonWorkFromJSONTyped(json: any, ignoreDiscriminator: boolean): TRViSJsonWork {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['Name'],
        'trains': ((json['Trains'] as Array<any>).map(TRViSJsonTrainFromJSON)),
        'affectDate': json['AffectDate'] == null ? undefined : (new Date(json['AffectDate'])),
        'affixContentType': json['AffixContentType'] == null ? undefined : json['AffixContentType'],
        'affixContent': json['AffixContent'] == null ? undefined : json['AffixContent'],
        'remarks': json['Remarks'] == null ? undefined : json['Remarks'],
        'hasETrainTimetable': json['HasETrainTimetable'] == null ? undefined : json['HasETrainTimetable'],
        'eTrainTimetableContentType': json['ETrainTimetableContentType'] == null ? undefined : json['ETrainTimetableContentType'],
        'eTrainTimetableContent': json['ETrainTimetableContent'] == null ? undefined : json['ETrainTimetableContent'],
    };
}

export function TRViSJsonWorkToJSON(value?: TRViSJsonWork | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Name': value['name'],
        'Trains': ((value['trains'] as Array<any>).map(TRViSJsonTrainToJSON)),
        'AffectDate': value['affectDate'] == null ? undefined : ((value['affectDate'] as any).toISOString().substring(0,10)),
        'AffixContentType': value['affixContentType'],
        'AffixContent': value['affixContent'],
        'Remarks': value['remarks'],
        'HasETrainTimetable': value['hasETrainTimetable'],
        'ETrainTimetableContentType': value['eTrainTimetableContentType'],
        'ETrainTimetableContent': value['eTrainTimetableContent'],
    };
}

