/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkGroupsPrivilege
 */
export interface WorkGroupsPrivilege {
    /**
     * 権限の種類
     * @type {string}
     * @memberof WorkGroupsPrivilege
     */
    privilegeType: WorkGroupsPrivilegePrivilegeTypeEnum;
    /**
     * UserID
     * @type {string}
     * @memberof WorkGroupsPrivilege
     */
    readonly uid?: string;
    /**
     * WorkGroupのID (UUID)
     * @type {string}
     * @memberof WorkGroupsPrivilege
     */
    readonly workGroupsId?: string;
    /**
     * InviteKeyのID (UUID)
     * @type {string}
     * @memberof WorkGroupsPrivilege
     */
    readonly inviteKeysId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof WorkGroupsPrivilege
     */
    readonly createdAt?: Date;
    /**
     * 更新日時
     * @type {Date}
     * @memberof WorkGroupsPrivilege
     */
    readonly updatedAt?: Date;
}


/**
 * @export
 */
export const WorkGroupsPrivilegePrivilegeTypeEnum = {
    Read: 'read',
    Write: 'write',
    Admin: 'admin'
} as const;
export type WorkGroupsPrivilegePrivilegeTypeEnum = typeof WorkGroupsPrivilegePrivilegeTypeEnum[keyof typeof WorkGroupsPrivilegePrivilegeTypeEnum];


/**
 * Check if a given object implements the WorkGroupsPrivilege interface.
 */
export function instanceOfWorkGroupsPrivilege(value: object): value is WorkGroupsPrivilege {
    if (!('privilegeType' in value) || value['privilegeType'] === undefined) return false;
    return true;
}

export function WorkGroupsPrivilegeFromJSON(json: any): WorkGroupsPrivilege {
    return WorkGroupsPrivilegeFromJSONTyped(json, false);
}

export function WorkGroupsPrivilegeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkGroupsPrivilege {
    if (json == null) {
        return json;
    }
    return {
        
        'privilegeType': json['privilege_type'],
        'uid': json['uid'] == null ? undefined : json['uid'],
        'workGroupsId': json['work_groups_id'] == null ? undefined : json['work_groups_id'],
        'inviteKeysId': json['invite_keys_id'] == null ? undefined : json['invite_keys_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function WorkGroupsPrivilegeToJSON(value?: Omit<WorkGroupsPrivilege, 'uid'|'work_groups_id'|'invite_keys_id'|'created_at'|'updated_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'privilege_type': value['privilegeType'],
    };
}

