/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Color8bit
 */
export interface Color8bit {
    /**
     * 色の赤色成分 (8bit)
     * @type {number}
     * @memberof Color8bit
     */
    red?: number;
    /**
     * 色の緑色成分 (8bit)
     * @type {number}
     * @memberof Color8bit
     */
    green?: number;
    /**
     * 色の青色成分 (8bit)
     * @type {number}
     * @memberof Color8bit
     */
    blue?: number;
}

/**
 * Check if a given object implements the Color8bit interface.
 */
export function instanceOfColor8bit(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Color8bitFromJSON(json: any): Color8bit {
    return Color8bitFromJSONTyped(json, false);
}

export function Color8bitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Color8bit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'red': !exists(json, 'red') ? undefined : json['red'],
        'green': !exists(json, 'green') ? undefined : json['green'],
        'blue': !exists(json, 'blue') ? undefined : json['blue'],
    };
}

export function Color8bitToJSON(value?: Color8bit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'red': value.red,
        'green': value.green,
        'blue': value.blue,
    };
}

