// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StationTrack
 */
export interface StationTrack {
    /**
     * Station Trackの説明
     * @type {string}
     * @memberof StationTrack
     */
    description: string;
    /**
     * その番線の名前
     * @type {string}
     * @memberof StationTrack
     */
    name: string;
    /**
     * Station TrackのID (UUID)
     * @type {string}
     * @memberof StationTrack
     */
    readonly stationTracksId?: string;
    /**
     * StationのID (UUID)
     * @type {string}
     * @memberof StationTrack
     */
    readonly stationsId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof StationTrack
     */
    readonly createdAt?: Date;
    /**
     * 進入制限のデフォルト値 (km/h)
     * @type {number}
     * @memberof StationTrack
     */
    runInLimit?: number;
    /**
     * 進出制限のデフォルト値 (km/h)
     * @type {number}
     * @memberof StationTrack
     */
    runOutLimit?: number;
}

/**
 * Check if a given object implements the StationTrack interface.
 */
export function instanceOfStationTrack(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function StationTrackFromJSON(json: any): StationTrack {
    return StationTrackFromJSONTyped(json, false);
}

export function StationTrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationTrack {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'name': json['name'],
        'stationTracksId': !exists(json, 'station_tracks_id') ? undefined : json['station_tracks_id'],
        'stationsId': !exists(json, 'stations_id') ? undefined : json['stations_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'runInLimit': !exists(json, 'run_in_limit') ? undefined : json['run_in_limit'],
        'runOutLimit': !exists(json, 'run_out_limit') ? undefined : json['run_out_limit'],
    };
}

export function StationTrackToJSON(value?: StationTrack | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
        'run_in_limit': value.runInLimit,
        'run_out_limit': value.runOutLimit,
    };
}

