// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Train
 */
export interface Train {
    /**
     * Train (列車) の説明
     * @type {string}
     * @memberof Train
     */
    description: string;
    /**
     * 列車番号
     * @type {string}
     * @memberof Train
     */
    trainNumber: string;
    /**
     * 進行方向 (0~1: 下り, -1: 上り)
     * @type {number}
     * @memberof Train
     */
    direction: number;
    /**
     * 仕業の初日からの経過日数 (0で初日/日勤、1で明け)
     * @type {number}
     * @memberof Train
     */
    dayCount: number;
    /**
     * TrainのID (UUID)
     * @type {string}
     * @memberof Train
     */
    readonly trainsId?: string;
    /**
     * WorkのID (UUID)
     * @type {string}
     * @memberof Train
     */
    readonly worksId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof Train
     */
    readonly createdAt?: Date;
    /**
     * 最高速度 (km/h)
     * @type {string}
     * @memberof Train
     */
    maxSpeed?: string;
    /**
     * 速度種別
     * @type {string}
     * @memberof Train
     */
    speedType?: string;
    /**
     * けん引定数
     * @type {string}
     * @memberof Train
     */
    nominalTractiveCapacity?: string;
    /**
     * 編成両数 (0以下で非表示)
     * @type {number}
     * @memberof Train
     */
    carCount?: number;
    /**
     * 行先
     * @type {string}
     * @memberof Train
     */
    destination?: string;
    /**
     * 乗車前の注意事項 (「乗継」など)
     * @type {string}
     * @memberof Train
     */
    beginRemarks?: string;
    /**
     * 降車後の注意事項 (「乗継」など)
     * @type {string}
     * @memberof Train
     */
    afterRemarks?: string;
    /**
     * 注意事項
     * @type {string}
     * @memberof Train
     */
    remarks?: string;
    /**
     * 発前
     * @type {string}
     * @memberof Train
     */
    beforeDeparture?: string;
    /**
     * 着後
     * @type {string}
     * @memberof Train
     */
    afterArrive?: string;
    /**
     * 列車に関する情報
     * @type {string}
     * @memberof Train
     */
    trainInfo?: string;
    /**
     * 添乗での移動かどうか
     * @type {boolean}
     * @memberof Train
     */
    isRideOnMoving?: boolean;
}

/**
 * Check if a given object implements the Train interface.
 */
export function instanceOfTrain(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "trainNumber" in value;
    isInstance = isInstance && "direction" in value;
    isInstance = isInstance && "dayCount" in value;

    return isInstance;
}

export function TrainFromJSON(json: any): Train {
    return TrainFromJSONTyped(json, false);
}

export function TrainFromJSONTyped(json: any, ignoreDiscriminator: boolean): Train {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'trainNumber': json['train_number'],
        'direction': json['direction'],
        'dayCount': json['day_count'],
        'trainsId': !exists(json, 'trains_id') ? undefined : json['trains_id'],
        'worksId': !exists(json, 'works_id') ? undefined : json['works_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'maxSpeed': !exists(json, 'max_speed') ? undefined : json['max_speed'],
        'speedType': !exists(json, 'speed_type') ? undefined : json['speed_type'],
        'nominalTractiveCapacity': !exists(json, 'nominal_tractive_capacity') ? undefined : json['nominal_tractive_capacity'],
        'carCount': !exists(json, 'car_count') ? undefined : json['car_count'],
        'destination': !exists(json, 'destination') ? undefined : json['destination'],
        'beginRemarks': !exists(json, 'begin_remarks') ? undefined : json['begin_remarks'],
        'afterRemarks': !exists(json, 'after_remarks') ? undefined : json['after_remarks'],
        'remarks': !exists(json, 'remarks') ? undefined : json['remarks'],
        'beforeDeparture': !exists(json, 'before_departure') ? undefined : json['before_departure'],
        'afterArrive': !exists(json, 'after_arrive') ? undefined : json['after_arrive'],
        'trainInfo': !exists(json, 'train_info') ? undefined : json['train_info'],
        'isRideOnMoving': !exists(json, 'is_ride_on_moving') ? undefined : json['is_ride_on_moving'],
    };
}

export function TrainToJSON(value?: Train | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'train_number': value.trainNumber,
        'direction': value.direction,
        'day_count': value.dayCount,
        'max_speed': value.maxSpeed,
        'speed_type': value.speedType,
        'nominal_tractive_capacity': value.nominalTractiveCapacity,
        'car_count': value.carCount,
        'destination': value.destination,
        'begin_remarks': value.beginRemarks,
        'after_remarks': value.afterRemarks,
        'remarks': value.remarks,
        'before_departure': value.beforeDeparture,
        'after_arrive': value.afterArrive,
        'train_info': value.trainInfo,
        'is_ride_on_moving': value.isRideOnMoving,
    };
}

