// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkGroup
 */
export interface WorkGroup {
    /**
     * WorkGroupの説明
     * @type {string}
     * @memberof WorkGroup
     */
    description: string;
    /**
     * WorkGroupの名前
     * @type {string}
     * @memberof WorkGroup
     */
    name: string;
    /**
     * WorkGroupのID (UUID)
     * @type {string}
     * @memberof WorkGroup
     */
    readonly workGroupsId?: string;
    /**
     * 作成日時
     * @type {Date}
     * @memberof WorkGroup
     */
    readonly createdAt?: Date;
    /**
     * 権限の種類
     * @type {string}
     * @memberof WorkGroup
     */
    readonly privilegeType?: WorkGroupPrivilegeTypeEnum;
}


/**
 * @export
 */
export const WorkGroupPrivilegeTypeEnum = {
    Read: 'read',
    Write: 'write',
    Admin: 'admin'
} as const;
export type WorkGroupPrivilegeTypeEnum = typeof WorkGroupPrivilegeTypeEnum[keyof typeof WorkGroupPrivilegeTypeEnum];


/**
 * Check if a given object implements the WorkGroup interface.
 */
export function instanceOfWorkGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function WorkGroupFromJSON(json: any): WorkGroup {
    return WorkGroupFromJSONTyped(json, false);
}

export function WorkGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'name': json['name'],
        'workGroupsId': !exists(json, 'work_groups_id') ? undefined : json['work_groups_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'privilegeType': !exists(json, 'privilege_type') ? undefined : json['privilege_type'],
    };
}

export function WorkGroupToJSON(value?: WorkGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
    };
}

