/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Line,
  Schema,
} from '../models/index';
import {
    LineFromJSON,
    LineToJSON,
    SchemaFromJSON,
    SchemaToJSON,
} from '../models/index';

export interface CreateLineRequest {
    projectId: string;
    line: Line;
}

export interface DeleteLineRequest {
    lineId: string;
}

export interface GetLineRequest {
    lineId: string;
}

export interface GetLineListRequest {
    projectId: string;
    p?: number;
    limit?: number;
    top?: string;
}

export interface UpdateLineRequest {
    lineId: string;
    line: Line;
}

/**
 * LineApi - interface
 * 
 * @export
 * @interface LineApiInterface
 */
export interface LineApiInterface {
    /**
     * 指定のProjectに属する Line (路線) を新しく作成する  このProjectへのWRITE権限が必要です。 
     * @summary 作成する
     * @param {string} projectId ProjectのID
     * @param {Line} line 作成するLineの情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineApiInterface
     */
    createLineRaw(requestParameters: CreateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Line>>;

    /**
     * 指定のProjectに属する Line (路線) を新しく作成する  このProjectへのWRITE権限が必要です。 
     * 作成する
     */
    createLine(requestParameters: CreateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Line>;

    /**
     * 既存の Line を削除する  このデータが属するProjectへのWRITE権限が必要です。 
     * @summary 削除する
     * @param {string} lineId LineのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineApiInterface
     */
    deleteLineRaw(requestParameters: DeleteLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * 既存の Line を削除する  このデータが属するProjectへのWRITE権限が必要です。 
     * 削除する
     */
    deleteLine(requestParameters: DeleteLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Line (路線) の情報を1件取得する  このデータが属するProjectへのREAD権限が必要です。 
     * @summary 1件取得する
     * @param {string} lineId LineのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineApiInterface
     */
    getLineRaw(requestParameters: GetLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Line>>;

    /**
     * Line (路線) の情報を1件取得する  このデータが属するProjectへのREAD権限が必要です。 
     * 1件取得する
     */
    getLine(requestParameters: GetLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Line>;

    /**
     * 指定のProjectに属する Line (路線) の情報を複数件取得する  このProjectへのREAD権限が必要です。 
     * @summary 複数件取得する
     * @param {string} projectId ProjectのID
     * @param {number} [p] ページングを行う場合のページ番号
     * @param {number} [limit] ページングを行う場合の1ページあたりの件数
     * @param {string} [top] ページングを行う場合の一番上に表示するID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineApiInterface
     */
    getLineListRaw(requestParameters: GetLineListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Line>>>;

    /**
     * 指定のProjectに属する Line (路線) の情報を複数件取得する  このProjectへのREAD権限が必要です。 
     * 複数件取得する
     */
    getLineList(requestParameters: GetLineListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Line>>;

    /**
     * 既存の Line の情報を更新する  このデータが属するProjectへのWRITE権限が必要です。 
     * @summary 更新する
     * @param {string} lineId LineのID
     * @param {Line} line 更新後のLineの情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LineApiInterface
     */
    updateLineRaw(requestParameters: UpdateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Line>>;

    /**
     * 既存の Line の情報を更新する  このデータが属するProjectへのWRITE権限が必要です。 
     * 更新する
     */
    updateLine(requestParameters: UpdateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Line>;

}

/**
 * 
 */
export class LineApi extends runtime.BaseAPI implements LineApiInterface {

    /**
     * 指定のProjectに属する Line (路線) を新しく作成する  このProjectへのWRITE権限が必要です。 
     * 作成する
     */
    async createLineRaw(requestParameters: CreateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Line>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling createLine.');
        }

        if (requestParameters.line === null || requestParameters.line === undefined) {
            throw new runtime.RequiredError('line','Required parameter requestParameters.line was null or undefined when calling createLine.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/lines`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LineToJSON(requestParameters.line),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LineFromJSON(jsonValue));
    }

    /**
     * 指定のProjectに属する Line (路線) を新しく作成する  このProjectへのWRITE権限が必要です。 
     * 作成する
     */
    async createLine(requestParameters: CreateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Line> {
        const response = await this.createLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 既存の Line を削除する  このデータが属するProjectへのWRITE権限が必要です。 
     * 削除する
     */
    async deleteLineRaw(requestParameters: DeleteLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.lineId === null || requestParameters.lineId === undefined) {
            throw new runtime.RequiredError('lineId','Required parameter requestParameters.lineId was null or undefined when calling deleteLine.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/lines/{lineId}`.replace(`{${"lineId"}}`, encodeURIComponent(String(requestParameters.lineId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 既存の Line を削除する  このデータが属するProjectへのWRITE権限が必要です。 
     * 削除する
     */
    async deleteLine(requestParameters: DeleteLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLineRaw(requestParameters, initOverrides);
    }

    /**
     * Line (路線) の情報を1件取得する  このデータが属するProjectへのREAD権限が必要です。 
     * 1件取得する
     */
    async getLineRaw(requestParameters: GetLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Line>> {
        if (requestParameters.lineId === null || requestParameters.lineId === undefined) {
            throw new runtime.RequiredError('lineId','Required parameter requestParameters.lineId was null or undefined when calling getLine.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/lines/{lineId}`.replace(`{${"lineId"}}`, encodeURIComponent(String(requestParameters.lineId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LineFromJSON(jsonValue));
    }

    /**
     * Line (路線) の情報を1件取得する  このデータが属するProjectへのREAD権限が必要です。 
     * 1件取得する
     */
    async getLine(requestParameters: GetLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Line> {
        const response = await this.getLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 指定のProjectに属する Line (路線) の情報を複数件取得する  このProjectへのREAD権限が必要です。 
     * 複数件取得する
     */
    async getLineListRaw(requestParameters: GetLineListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Line>>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling getLineList.');
        }

        const queryParameters: any = {};

        if (requestParameters.p !== undefined) {
            queryParameters['p'] = requestParameters.p;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.top !== undefined) {
            queryParameters['top'] = requestParameters.top;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/lines`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LineFromJSON));
    }

    /**
     * 指定のProjectに属する Line (路線) の情報を複数件取得する  このProjectへのREAD権限が必要です。 
     * 複数件取得する
     */
    async getLineList(requestParameters: GetLineListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Line>> {
        const response = await this.getLineListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 既存の Line の情報を更新する  このデータが属するProjectへのWRITE権限が必要です。 
     * 更新する
     */
    async updateLineRaw(requestParameters: UpdateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Line>> {
        if (requestParameters.lineId === null || requestParameters.lineId === undefined) {
            throw new runtime.RequiredError('lineId','Required parameter requestParameters.lineId was null or undefined when calling updateLine.');
        }

        if (requestParameters.line === null || requestParameters.line === undefined) {
            throw new runtime.RequiredError('line','Required parameter requestParameters.line was null or undefined when calling updateLine.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/lines/{lineId}`.replace(`{${"lineId"}}`, encodeURIComponent(String(requestParameters.lineId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LineToJSON(requestParameters.line),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LineFromJSON(jsonValue));
    }

    /**
     * 既存の Line の情報を更新する  このデータが属するProjectへのWRITE権限が必要です。 
     * 更新する
     */
    async updateLine(requestParameters: UpdateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Line> {
        const response = await this.updateLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
