/* tslint:disable */
/* eslint-disable */
/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Project,
  ProjectsPrivilege,
  Schema,
} from '../models/index';
import {
    ProjectFromJSON,
    ProjectToJSON,
    ProjectsPrivilegeFromJSON,
    ProjectsPrivilegeToJSON,
    SchemaFromJSON,
    SchemaToJSON,
} from '../models/index';

export interface CreateProjectRequest {
    project: Project;
}

export interface DeleteProjectRequest {
    projectId: string;
}

export interface GetProjectRequest {
    projectId: string;
}

export interface GetProjectListRequest {
    p?: number;
    limit?: number;
    top?: string;
}

export interface GetProjectPrivilegeRequest {
    projectId: string;
    uid?: string;
    uidAnonymous?: boolean;
}

export interface UpdateProjectRequest {
    projectId: string;
    project: Project;
}

export interface UpdateProjectPrivilegeRequest {
    projectId: string;
    projectsPrivilege: ProjectsPrivilege;
    uid?: string;
    uidAnonymous?: boolean;
}

/**
 * ProjectApi - interface
 * 
 * @export
 * @interface ProjectApiInterface
 */
export interface ProjectApiInterface {
    /**
     * Project を新しく作成する  この操作にはサインインが必要です。 
     * @summary 作成する
     * @param {Project} project 作成するProjectの情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    createProjectRaw(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>>;

    /**
     * Project を新しく作成する  この操作にはサインインが必要です。 
     * 作成する
     */
    createProject(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project>;

    /**
     * 既存の Project を削除する  このProjectへのADMIN権限が必要です。 
     * @summary 削除する
     * @param {string} projectId ProjectのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    deleteProjectRaw(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * 既存の Project を削除する  このProjectへのADMIN権限が必要です。 
     * 削除する
     */
    deleteProject(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Project の情報を1件取得する  このProjectへのREAD権限が必要です。 
     * @summary 1件取得する
     * @param {string} projectId ProjectのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    getProjectRaw(requestParameters: GetProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>>;

    /**
     * Project の情報を1件取得する  このProjectへのREAD権限が必要です。 
     * 1件取得する
     */
    getProject(requestParameters: GetProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project>;

    /**
     * 自身が取得できる Project の情報を複数件取得する 
     * @summary 複数件取得する
     * @param {number} [p] ページングを行う場合のページ番号
     * @param {number} [limit] ページングを行う場合の1ページあたりの件数
     * @param {string} [top] ページングを行う場合の一番上に表示するID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    getProjectListRaw(requestParameters: GetProjectListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>>;

    /**
     * 自身が取得できる Project の情報を複数件取得する 
     * 複数件取得する
     */
    getProjectList(requestParameters: GetProjectListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>>;

    /**
     * このProjectに関する自身の権限を取得する。  管理者の場合は、指定のユーザの権限を取得することも可能。 
     * @summary 権限情報を取得する
     * @param {string} projectId ProjectのID
     * @param {string} [uid] ユーザのID
     * @param {boolean} [uidAnonymous] 匿名ユーザ・すべてのユーザに対する操作か  &#x60;uid&#x60; が指定された場合、そちらが優先される 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    getProjectPrivilegeRaw(requestParameters: GetProjectPrivilegeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsPrivilege>>;

    /**
     * このProjectに関する自身の権限を取得する。  管理者の場合は、指定のユーザの権限を取得することも可能。 
     * 権限情報を取得する
     */
    getProjectPrivilege(requestParameters: GetProjectPrivilegeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsPrivilege>;

    /**
     * 既存の Project を更新する  このProjectへのWRITE権限が必要です。 
     * @summary 更新する
     * @param {string} projectId ProjectのID
     * @param {Project} project 更新後のProjectの情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    updateProjectRaw(requestParameters: UpdateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>>;

    /**
     * 既存の Project を更新する  このProjectへのWRITE権限が必要です。 
     * 更新する
     */
    updateProject(requestParameters: UpdateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project>;

    /**
     * このProjectに対する自身の権限を更新する。(現在の権限以下の権限のみ設定可能)  管理者の場合は、指定のユーザの権限を追加・更新することも可能。(invite_key_idはNULLになります) 
     * @summary 権限を更新する
     * @param {string} projectId ProjectのID
     * @param {ProjectsPrivilege} projectsPrivilege 更新後の権限情報
     * @param {string} [uid] ユーザのID
     * @param {boolean} [uidAnonymous] 匿名ユーザ・すべてのユーザに対する操作か  &#x60;uid&#x60; が指定された場合、そちらが優先される 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApiInterface
     */
    updateProjectPrivilegeRaw(requestParameters: UpdateProjectPrivilegeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsPrivilege>>;

    /**
     * このProjectに対する自身の権限を更新する。(現在の権限以下の権限のみ設定可能)  管理者の場合は、指定のユーザの権限を追加・更新することも可能。(invite_key_idはNULLになります) 
     * 権限を更新する
     */
    updateProjectPrivilege(requestParameters: UpdateProjectPrivilegeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsPrivilege>;

}

/**
 * 
 */
export class ProjectApi extends runtime.BaseAPI implements ProjectApiInterface {

    /**
     * Project を新しく作成する  この操作にはサインインが必要です。 
     * 作成する
     */
    async createProjectRaw(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        if (requestParameters.project === null || requestParameters.project === undefined) {
            throw new runtime.RequiredError('project','Required parameter requestParameters.project was null or undefined when calling createProject.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectToJSON(requestParameters.project),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     * Project を新しく作成する  この操作にはサインインが必要です。 
     * 作成する
     */
    async createProject(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.createProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 既存の Project を削除する  このProjectへのADMIN権限が必要です。 
     * 削除する
     */
    async deleteProjectRaw(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling deleteProject.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 既存の Project を削除する  このProjectへのADMIN権限が必要です。 
     * 削除する
     */
    async deleteProject(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProjectRaw(requestParameters, initOverrides);
    }

    /**
     * Project の情報を1件取得する  このProjectへのREAD権限が必要です。 
     * 1件取得する
     */
    async getProjectRaw(requestParameters: GetProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling getProject.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     * Project の情報を1件取得する  このProjectへのREAD権限が必要です。 
     * 1件取得する
     */
    async getProject(requestParameters: GetProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.getProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 自身が取得できる Project の情報を複数件取得する 
     * 複数件取得する
     */
    async getProjectListRaw(requestParameters: GetProjectListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>> {
        const queryParameters: any = {};

        if (requestParameters.p !== undefined) {
            queryParameters['p'] = requestParameters.p;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.top !== undefined) {
            queryParameters['top'] = requestParameters.top;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectFromJSON));
    }

    /**
     * 自身が取得できる Project の情報を複数件取得する 
     * 複数件取得する
     */
    async getProjectList(requestParameters: GetProjectListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>> {
        const response = await this.getProjectListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * このProjectに関する自身の権限を取得する。  管理者の場合は、指定のユーザの権限を取得することも可能。 
     * 権限情報を取得する
     */
    async getProjectPrivilegeRaw(requestParameters: GetProjectPrivilegeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsPrivilege>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling getProjectPrivilege.');
        }

        const queryParameters: any = {};

        if (requestParameters.uid !== undefined) {
            queryParameters['uid'] = requestParameters.uid;
        }

        if (requestParameters.uidAnonymous !== undefined) {
            queryParameters['uid-anonymous'] = requestParameters.uidAnonymous;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/privileges`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsPrivilegeFromJSON(jsonValue));
    }

    /**
     * このProjectに関する自身の権限を取得する。  管理者の場合は、指定のユーザの権限を取得することも可能。 
     * 権限情報を取得する
     */
    async getProjectPrivilege(requestParameters: GetProjectPrivilegeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsPrivilege> {
        const response = await this.getProjectPrivilegeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 既存の Project を更新する  このProjectへのWRITE権限が必要です。 
     * 更新する
     */
    async updateProjectRaw(requestParameters: UpdateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling updateProject.');
        }

        if (requestParameters.project === null || requestParameters.project === undefined) {
            throw new runtime.RequiredError('project','Required parameter requestParameters.project was null or undefined when calling updateProject.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectToJSON(requestParameters.project),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
    }

    /**
     * 既存の Project を更新する  このProjectへのWRITE権限が必要です。 
     * 更新する
     */
    async updateProject(requestParameters: UpdateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
        const response = await this.updateProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * このProjectに対する自身の権限を更新する。(現在の権限以下の権限のみ設定可能)  管理者の場合は、指定のユーザの権限を追加・更新することも可能。(invite_key_idはNULLになります) 
     * 権限を更新する
     */
    async updateProjectPrivilegeRaw(requestParameters: UpdateProjectPrivilegeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsPrivilege>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling updateProjectPrivilege.');
        }

        if (requestParameters.projectsPrivilege === null || requestParameters.projectsPrivilege === undefined) {
            throw new runtime.RequiredError('projectsPrivilege','Required parameter requestParameters.projectsPrivilege was null or undefined when calling updateProjectPrivilege.');
        }

        const queryParameters: any = {};

        if (requestParameters.uid !== undefined) {
            queryParameters['uid'] = requestParameters.uid;
        }

        if (requestParameters.uidAnonymous !== undefined) {
            queryParameters['uid-anonymous'] = requestParameters.uidAnonymous;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/privileges`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectsPrivilegeToJSON(requestParameters.projectsPrivilege),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsPrivilegeFromJSON(jsonValue));
    }

    /**
     * このProjectに対する自身の権限を更新する。(現在の権限以下の権限のみ設定可能)  管理者の場合は、指定のユーザの権限を追加・更新することも可能。(invite_key_idはNULLになります) 
     * 権限を更新する
     */
    async updateProjectPrivilege(requestParameters: UpdateProjectPrivilegeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsPrivilege> {
        const response = await this.updateProjectPrivilegeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
