Project:
  type: object
  title: Project
  required:
    - description
    - name
  properties:
    projects_id:
      type: string
      format: uuid
      readOnly: true
      description: ProjectのID (UUID)
    created_at:
      type: string
      format: date-time
      readOnly: true
      description: 作成日時
    description:
      type: string
      description: Projectの説明
      example: Projectの説明が入ります
    name:
      type: string
      description: Projectの名前
      example: AAA鉄道
    privilege_type:
      type: string
      description: 権限の種類
      readOnly: true
      enum:
        - read
        - write
        - admin
      example: admin

ProjectArray:
  type: array
  title: ProjectArray
  items:
    $ref: '#/Project'
