<?php

/**
 * TRViS用 時刻表管理用API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class TimetableRowController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation createTimetableRow
     *
     * 作成する.
     *
     * @param string $workGroupId WorkGroupのID (required)
     * @param string $workId WorkのID (required)
     * @param string $trainId TrainのID (required)
     *
     * @return Http response
     */
    public function createTimetableRow($workGroupId, $workId, $trainId)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing createTimetableRow as a post method ?');
    }
    /**
     * Operation getTimetableRowList
     *
     * 複数件取得する.
     *
     * @param string $workGroupId WorkGroupのID (required)
     * @param string $workId WorkのID (required)
     * @param string $trainId TrainのID (required)
     *
     * @return Http response
     */
    public function getTimetableRowList($workGroupId, $workId, $trainId)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getTimetableRowList as a get method ?');
    }
    /**
     * Operation deleteTimetableRow
     *
     * 削除する.
     *
     * @param string $workGroupId WorkGroupのID (required)
     * @param string $workId WorkのID (required)
     * @param string $trainId TrainのID (required)
     * @param string $timetableRowId Timetable RowのID (required)
     *
     * @return Http response
     */
    public function deleteTimetableRow($workGroupId, $workId, $trainId, $timetableRowId)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteTimetableRow as a delete method ?');
    }
    /**
     * Operation getTimetableRow
     *
     * 1件取得する.
     *
     * @param string $workGroupId WorkGroupのID (required)
     * @param string $workId WorkのID (required)
     * @param string $trainId TrainのID (required)
     * @param string $timetableRowId Timetable RowのID (required)
     *
     * @return Http response
     */
    public function getTimetableRow($workGroupId, $workId, $trainId, $timetableRowId)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getTimetableRow as a get method ?');
    }
    /**
     * Operation updateTimetableRow
     *
     * 更新する.
     *
     * @param string $workGroupId WorkGroupのID (required)
     * @param string $workId WorkのID (required)
     * @param string $trainId TrainのID (required)
     * @param string $timetableRowId Timetable RowのID (required)
     *
     * @return Http response
     */
    public function updateTimetableRow($workGroupId, $workId, $trainId, $timetableRowId)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateTimetableRow as a put method ?');
    }
}
