<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace dev_t0r\trvis_backend\model;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\CoversMethod;
use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\model\ProjectStation;

/**
 * ProjectStationTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
#[CoversClass(\dev_t0r\trvis_backend\model\ProjectStation::class)]
#[CoversMethod(\dev_t0r\trvis_backend\model\ProjectStation::class, 'getOpenApiSchema')]
class ProjectStationTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProjectStation"
     */
    public function testProjectStation()
    {
        $testProjectStation = new ProjectStation();
        $namespacedClassname = ProjectStation::getModelsNamespace() . '\\ProjectStation';
        $this->assertSame('\\' . ProjectStation::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $this->markTestIncomplete(
            'Test of "name" property in "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "projectStationsId"
     */
    public function testPropertyProjectStationsId()
    {
        $this->markTestIncomplete(
            'Test of "projectStationsId" property in "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "projectsId"
     */
    public function testPropertyProjectsId()
    {
        $this->markTestIncomplete(
            'Test of "projectsId" property in "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
        $this->markTestIncomplete(
            'Test of "createdAt" property in "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "fullName"
     */
    public function testPropertyFullName()
    {
        $this->markTestIncomplete(
            'Test of "fullName" property in "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "locationLonlat"
     */
    public function testPropertyLocationLonlat()
    {
        $this->markTestIncomplete(
            'Test of "locationLonlat" property in "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "onStationDetectRadiusM"
     */
    public function testPropertyOnStationDetectRadiusM()
    {
        $this->markTestIncomplete(
            'Test of "onStationDetectRadiusM" property in "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "alwaysShowHh"
     */
    public function testPropertyAlwaysShowHh()
    {
        $this->markTestIncomplete(
            'Test of "alwaysShowHh" property in "ProjectStation" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = ProjectStation::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
