<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace dev_t0r\trvis_backend\model;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\model\StationLocationLonlat;

/**
 * StationLocationLonlatTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\model\StationLocationLonlat
 */
class StationLocationLonlatTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StationLocationLonlat"
     */
    public function testStationLocationLonlat()
    {
        $testStationLocationLonlat = new StationLocationLonlat();
        $namespacedClassname = StationLocationLonlat::getModelsNamespace() . '\\StationLocationLonlat';
        $this->assertSame('\\' . StationLocationLonlat::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "StationLocationLonlat" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
        $this->markTestIncomplete(
            'Test of "longitude" property in "StationLocationLonlat" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
        $this->markTestIncomplete(
            'Test of "latitude" property in "StationLocationLonlat" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = StationLocationLonlat::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
