<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace dev_t0r\trvis_backend\model;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\CoversMethod;
use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\model\StationOnLine;

/**
 * StationOnLineTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
#[CoversClass(\dev_t0r\trvis_backend\model\StationOnLine::class)]
#[CoversMethod(\dev_t0r\trvis_backend\model\StationOnLine::class, 'getOpenApiSchema')]
class StationOnLineTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StationOnLine"
     */
    public function testStationOnLine()
    {
        $testStationOnLine = new StationOnLine();
        $namespacedClassname = StationOnLine::getModelsNamespace() . '\\StationOnLine';
        $this->assertSame('\\' . StationOnLine::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "linesId"
     */
    public function testPropertyLinesId()
    {
        $this->markTestIncomplete(
            'Test of "linesId" property in "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "projectStationsId"
     */
    public function testPropertyProjectStationsId()
    {
        $this->markTestIncomplete(
            'Test of "projectStationsId" property in "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "locationM"
     */
    public function testPropertyLocationM()
    {
        $this->markTestIncomplete(
            'Test of "locationM" property in "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "stationsOnLineId"
     */
    public function testPropertyStationsOnLineId()
    {
        $this->markTestIncomplete(
            'Test of "stationsOnLineId" property in "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "projectsId"
     */
    public function testPropertyProjectsId()
    {
        $this->markTestIncomplete(
            'Test of "projectsId" property in "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
        $this->markTestIncomplete(
            'Test of "createdAt" property in "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "locationLonlat"
     */
    public function testPropertyLocationLonlat()
    {
        $this->markTestIncomplete(
            'Test of "locationLonlat" property in "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trackHiddenByDefault"
     */
    public function testPropertyTrackHiddenByDefault()
    {
        $this->markTestIncomplete(
            'Test of "trackHiddenByDefault" property in "StationOnLine" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = StationOnLine::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
