<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace dev_t0r\trvis_backend\model;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\model\StopPatternRow;

/**
 * StopPatternRowTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\model\StopPatternRow
 */
class StopPatternRowTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StopPatternRow"
     */
    public function testStopPatternRow()
    {
        $testStopPatternRow = new StopPatternRow();
        $namespacedClassname = StopPatternRow::getModelsNamespace() . '\\StopPatternRow';
        $this->assertSame('\\' . StopPatternRow::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "projectStationsId"
     */
    public function testPropertyProjectStationsId()
    {
        $this->markTestIncomplete(
            'Test of "projectStationsId" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "stopPatternRowsId"
     */
    public function testPropertyStopPatternRowsId()
    {
        $this->markTestIncomplete(
            'Test of "stopPatternRowsId" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "stopPatternsId"
     */
    public function testPropertyStopPatternsId()
    {
        $this->markTestIncomplete(
            'Test of "stopPatternsId" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "projectsId"
     */
    public function testPropertyProjectsId()
    {
        $this->markTestIncomplete(
            'Test of "projectsId" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
        $this->markTestIncomplete(
            'Test of "createdAt" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "sortKey"
     */
    public function testPropertySortKey()
    {
        $this->markTestIncomplete(
            'Test of "sortKey" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trackName"
     */
    public function testPropertyTrackName()
    {
        $this->markTestIncomplete(
            'Test of "trackName" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trackHidden"
     */
    public function testPropertyTrackHidden()
    {
        $this->markTestIncomplete(
            'Test of "trackHidden" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "isOperationOnlyStop"
     */
    public function testPropertyIsOperationOnlyStop()
    {
        $this->markTestIncomplete(
            'Test of "isOperationOnlyStop" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "isPass"
     */
    public function testPropertyIsPass()
    {
        $this->markTestIncomplete(
            'Test of "isPass" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "driveTimeMm"
     */
    public function testPropertyDriveTimeMm()
    {
        $this->markTestIncomplete(
            'Test of "driveTimeMm" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "driveTimeSs"
     */
    public function testPropertyDriveTimeSs()
    {
        $this->markTestIncomplete(
            'Test of "driveTimeSs" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "dwellTimeMm"
     */
    public function testPropertyDwellTimeMm()
    {
        $this->markTestIncomplete(
            'Test of "dwellTimeMm" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "dwellTimeSs"
     */
    public function testPropertyDwellTimeSs()
    {
        $this->markTestIncomplete(
            'Test of "dwellTimeSs" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "showArrive"
     */
    public function testPropertyShowArrive()
    {
        $this->markTestIncomplete(
            'Test of "showArrive" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "showDeparture"
     */
    public function testPropertyShowDeparture()
    {
        $this->markTestIncomplete(
            'Test of "showDeparture" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "arriveStr"
     */
    public function testPropertyArriveStr()
    {
        $this->markTestIncomplete(
            'Test of "arriveStr" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "departureStr"
     */
    public function testPropertyDepartureStr()
    {
        $this->markTestIncomplete(
            'Test of "departureStr" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "runInLimit"
     */
    public function testPropertyRunInLimit()
    {
        $this->markTestIncomplete(
            'Test of "runInLimit" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "runOutLimit"
     */
    public function testPropertyRunOutLimit()
    {
        $this->markTestIncomplete(
            'Test of "runOutLimit" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "remarks"
     */
    public function testPropertyRemarks()
    {
        $this->markTestIncomplete(
            'Test of "remarks" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "alwaysShowHh"
     */
    public function testPropertyAlwaysShowHh()
    {
        $this->markTestIncomplete(
            'Test of "alwaysShowHh" property in "StopPatternRow" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = StopPatternRow::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
