<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace dev_t0r\trvis_backend\model;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\model\TimetableRow;

/**
 * TimetableRowTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\model\TimetableRow
 */
class TimetableRowTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TimetableRow"
     */
    public function testTimetableRow()
    {
        $testTimetableRow = new TimetableRow();
        $namespacedClassname = TimetableRow::getModelsNamespace() . '\\TimetableRow';
        $this->assertSame('\\' . TimetableRow::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "timetableRowsId"
     */
    public function testPropertyTimetableRowsId()
    {
        $this->markTestIncomplete(
            'Test of "timetableRowsId" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trainsId"
     */
    public function testPropertyTrainsId()
    {
        $this->markTestIncomplete(
            'Test of "trainsId" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "stationsId"
     */
    public function testPropertyStationsId()
    {
        $this->markTestIncomplete(
            'Test of "stationsId" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "stationTracksId"
     */
    public function testPropertyStationTracksId()
    {
        $this->markTestIncomplete(
            'Test of "stationTracksId" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "colorsIdMarker"
     */
    public function testPropertyColorsIdMarker()
    {
        $this->markTestIncomplete(
            'Test of "colorsIdMarker" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        $this->markTestIncomplete(
            'Test of "description" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
        $this->markTestIncomplete(
            'Test of "createdAt" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {
        $this->markTestIncomplete(
            'Test of "updatedAt" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "driveTimeMm"
     */
    public function testPropertyDriveTimeMm()
    {
        $this->markTestIncomplete(
            'Test of "driveTimeMm" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "driveTimeSs"
     */
    public function testPropertyDriveTimeSs()
    {
        $this->markTestIncomplete(
            'Test of "driveTimeSs" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "isOperationOnlyStop"
     */
    public function testPropertyIsOperationOnlyStop()
    {
        $this->markTestIncomplete(
            'Test of "isOperationOnlyStop" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "isPass"
     */
    public function testPropertyIsPass()
    {
        $this->markTestIncomplete(
            'Test of "isPass" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "hasBracket"
     */
    public function testPropertyHasBracket()
    {
        $this->markTestIncomplete(
            'Test of "hasBracket" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "isLastStop"
     */
    public function testPropertyIsLastStop()
    {
        $this->markTestIncomplete(
            'Test of "isLastStop" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "arriveTimeHh"
     */
    public function testPropertyArriveTimeHh()
    {
        $this->markTestIncomplete(
            'Test of "arriveTimeHh" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "arriveTimeMm"
     */
    public function testPropertyArriveTimeMm()
    {
        $this->markTestIncomplete(
            'Test of "arriveTimeMm" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "arriveTimeSs"
     */
    public function testPropertyArriveTimeSs()
    {
        $this->markTestIncomplete(
            'Test of "arriveTimeSs" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "departureTimeHh"
     */
    public function testPropertyDepartureTimeHh()
    {
        $this->markTestIncomplete(
            'Test of "departureTimeHh" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "departureTimeMm"
     */
    public function testPropertyDepartureTimeMm()
    {
        $this->markTestIncomplete(
            'Test of "departureTimeMm" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "departureTimeSs"
     */
    public function testPropertyDepartureTimeSs()
    {
        $this->markTestIncomplete(
            'Test of "departureTimeSs" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "runInLimit"
     */
    public function testPropertyRunInLimit()
    {
        $this->markTestIncomplete(
            'Test of "runInLimit" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "runOutLimit"
     */
    public function testPropertyRunOutLimit()
    {
        $this->markTestIncomplete(
            'Test of "runOutLimit" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "remarks"
     */
    public function testPropertyRemarks()
    {
        $this->markTestIncomplete(
            'Test of "remarks" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "arriveStr"
     */
    public function testPropertyArriveStr()
    {
        $this->markTestIncomplete(
            'Test of "arriveStr" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "departureStr"
     */
    public function testPropertyDepartureStr()
    {
        $this->markTestIncomplete(
            'Test of "departureStr" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "markerText"
     */
    public function testPropertyMarkerText()
    {
        $this->markTestIncomplete(
            'Test of "markerText" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "workType"
     */
    public function testPropertyWorkType()
    {
        $this->markTestIncomplete(
            'Test of "workType" property in "TimetableRow" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = TimetableRow::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
