<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace dev_t0r\trvis_backend\model;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\model\Train;

/**
 * TrainTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\model\Train
 */
class TrainTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Train"
     */
    public function testTrain()
    {
        $testTrain = new Train();
        $namespacedClassname = Train::getModelsNamespace() . '\\Train';
        $this->assertSame('\\' . Train::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        $this->markTestIncomplete(
            'Test of "description" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trainNumber"
     */
    public function testPropertyTrainNumber()
    {
        $this->markTestIncomplete(
            'Test of "trainNumber" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
        $this->markTestIncomplete(
            'Test of "direction" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "dayCount"
     */
    public function testPropertyDayCount()
    {
        $this->markTestIncomplete(
            'Test of "dayCount" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trainId"
     */
    public function testPropertyTrainId()
    {
        $this->markTestIncomplete(
            'Test of "trainId" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
        $this->markTestIncomplete(
            'Test of "createdAt" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "maxSpeed"
     */
    public function testPropertyMaxSpeed()
    {
        $this->markTestIncomplete(
            'Test of "maxSpeed" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "speedType"
     */
    public function testPropertySpeedType()
    {
        $this->markTestIncomplete(
            'Test of "speedType" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "nominalTractiveCapacity"
     */
    public function testPropertyNominalTractiveCapacity()
    {
        $this->markTestIncomplete(
            'Test of "nominalTractiveCapacity" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "carCount"
     */
    public function testPropertyCarCount()
    {
        $this->markTestIncomplete(
            'Test of "carCount" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
        $this->markTestIncomplete(
            'Test of "destination" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "beginRemarks"
     */
    public function testPropertyBeginRemarks()
    {
        $this->markTestIncomplete(
            'Test of "beginRemarks" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "afterRemarks"
     */
    public function testPropertyAfterRemarks()
    {
        $this->markTestIncomplete(
            'Test of "afterRemarks" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "remarks"
     */
    public function testPropertyRemarks()
    {
        $this->markTestIncomplete(
            'Test of "remarks" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "beforeDeparture"
     */
    public function testPropertyBeforeDeparture()
    {
        $this->markTestIncomplete(
            'Test of "beforeDeparture" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "afterArrive"
     */
    public function testPropertyAfterArrive()
    {
        $this->markTestIncomplete(
            'Test of "afterArrive" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trainInfo"
     */
    public function testPropertyTrainInfo()
    {
        $this->markTestIncomplete(
            'Test of "trainInfo" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "isRideOnMoving"
     */
    public function testPropertyIsRideOnMoving()
    {
        $this->markTestIncomplete(
            'Test of "isRideOnMoving" property in "Train" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Train::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
