<?php

/**
 * TRViS用 時刻表管理用API
 * PHP version 7.4
 *
 * @package dev_t0r
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace dev_t0r\trvis_backend\model;

use PHPUnit\Framework\TestCase;
use dev_t0r\trvis_backend\model\TRViSJsonWork;

/**
 * TRViSJsonWorkTest Class Doc Comment
 *
 * @package dev_t0r\trvis_backend\model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \dev_t0r\trvis_backend\model\TRViSJsonWork
 */
class TRViSJsonWorkTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TRViSJsonWork"
     */
    public function testTRViSJsonWork()
    {
        $testTRViSJsonWork = new TRViSJsonWork();
        $namespacedClassname = TRViSJsonWork::getModelsNamespace() . '\\TRViSJsonWork';
        $this->assertSame('\\' . TRViSJsonWork::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $this->markTestIncomplete(
            'Test of "name" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "trains"
     */
    public function testPropertyTrains()
    {
        $this->markTestIncomplete(
            'Test of "trains" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "affectDate"
     */
    public function testPropertyAffectDate()
    {
        $this->markTestIncomplete(
            'Test of "affectDate" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "affixContentType"
     */
    public function testPropertyAffixContentType()
    {
        $this->markTestIncomplete(
            'Test of "affixContentType" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "affixContent"
     */
    public function testPropertyAffixContent()
    {
        $this->markTestIncomplete(
            'Test of "affixContent" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "remarks"
     */
    public function testPropertyRemarks()
    {
        $this->markTestIncomplete(
            'Test of "remarks" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "hasETrainTimetable"
     */
    public function testPropertyHasETrainTimetable()
    {
        $this->markTestIncomplete(
            'Test of "hasETrainTimetable" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "eTrainTimetableContentType"
     */
    public function testPropertyETrainTimetableContentType()
    {
        $this->markTestIncomplete(
            'Test of "eTrainTimetableContentType" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "eTrainTimetableContent"
     */
    public function testPropertyETrainTimetableContent()
    {
        $this->markTestIncomplete(
            'Test of "eTrainTimetableContent" property in "TRViSJsonWork" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = TRViSJsonWork::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
